---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pg-user-immich
  namespace: postgres
spec:
  encryptedData:
    password: AgClDOHvDTUU0VttZ95xcyFrKhgHy4oHdNdTHonQxmbMlpU4YXyjUDECmPv66N0thDvW8l8vxLy8L9NNYKjJ1tt/z0bUVUk/GD5Rebm0bUJ/8Z8m5iiUHQNF9OTcQf7V8jlTFPm8btUFQZmnVgZ3nlukhdIwB76HgsNYa+Pga0cv6eQrq6elpaahx/uBymbfNZ9XROnLmXUunaE5apmmThbm29QrzIIsBZY89FaqYIl85FyD2g5ZmbdPJrq1SgD11Ql67ksDkMRhZyWP9z2sySp7rSS8Ds+trFR/z+lj5sEHTS4MoUy2QZoalyRQdv6N54IgOfdlnSK4UY/y/WAOFELO8KR2GefLET8qiLWOuuYz3SI8qtC0DE7viYIb9n9zHS5fHajAAANu3IXagcNLD+BMoSndkblLAipgamXxoBQoWLNuZryE2xFX71HEzgH+be2EF6I07YaYaCO4rg4OrkRcgNCVZXVVieLF6b66L/ObKsM9etbelYdi/GjW+lmZNRPNIuuwgND93hNRU1JupWlQlkE8IWW9qlXaUbL8vDVtPHdMUuhTrj+2rm+ptioyKWPQnozqswxjM+Wkzp8MrgdBPSLjg5gZmB6fteqCvFGHWmjAIQn2GEKKUl2Ofh0josChqQxe10ybIAncFE1oQgFkH+NgG1PFB1UX7JOtMMPzXVSiOjedsrSUmrZ012nuySE1Nj5GRYt9
    username: AgDS72rEbKT5gSjQlfPyu666orhRTCKduEaL/6cyD2ykRTL7wqKkqGv9G87g3g22XhU6VzMvMz6qyEWO/fI1kBLfl2SUXV+VkZ51/Bl3Cu+3Rft2ICPZsfwsVF0iL1f/Wm9q/YHEN9QhCp2TKk3K4GyPKB51VV+5Xcws7FxDkC1MhmdFNLdbaYp0iFi01k62owKckqArSqbKkTbaEEsKygjodhB2xSCcVp1TN0V2k5WVJqACqGDJM8YXZv9FqnFrg427yvOhSonoeiq46Oeqbefg9hhf1aBeZa8BqpaEVzANxBoKsAWdIkTBrgL8aRGPOLCsp/wlcpi0eURHeSPz0viBZTFDCeSY362UsV3t2BNFGrF7u00L62tupnymS5YvKk+RdS7H2+pOKLt2LcpdUfoE0RcBh1agxdobaHzKnBrDx+30FsJ10kEBoXFDpS3zQ8B4FCtLF2XO4rvjXqai5vYv6xViP4g8mmaCRh/xA89eZPfbHQ3BLU5zYbTC6UxLLaCEC0ZCpGSpFs7Ilzztrz+t5d95nkB1i1Zzw7MeDPn7RPx5FfbXcwJ0euPlrtcnVFTUKxfHerGK2Ow5o10SzrRwJjqkYs4MqUANtPIeD6oTHMa4D4farXkOaOuinH1SWLrSrylxJnEyhjsWQPSUJkV5SXRYzInrLqFTRNFvLKBVH475B/e36AZOaD1bWT1mpvE0ZDy1F5sh
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: pg-user-immich
      namespace: postgres
    type: kubernetes.io/basic-auth
