---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-inkture
  namespace: flux-system
spec:
  encryptedData:
    identity: AgCn5VGG0u//jQ6l8QaMpPv2g7dxs6RVonVWGnSKYg8+pdP/Q6dGL3B9VSkZoPQkwmLB1oCRJqDa8ESOq4/t8JnKzzH8dDczvSPEv/RmrtudtHWTDVjI9F2LTnKO+ER2pzhmsSBM2b7ROLKau1ldO6pBPZAmHUzYbqMy6b0PZVhnidltUDJFKm0r8CuOYkh07lHB5bX4Ctc/oA1DcCMpdpXWNZ8MnhbKizeG3HcHX31setwyvxf3ha8cSZfDMW3tVqoR5I1hOihOuUCm7Ip32nc06+Ps/aVNx9W+KRyz5ddwk3RbyQvMMRmiWObiFXCXKGolyiEvkiUYzeUml7AcLigc/Z65mRQzOGRSqKeN/3E2hBaUmEaSa3uanUXzuusgl6LRv5l9c9sU/CnVyxlYTTYbUnxIKEsnTnI0QJCUGAY+YXxn5ORtc7fT9lZbhIyBFRAun2SqNRMV2A4POwB966gcefHmYSnw9yWnf9mDz/9GCm5AXnFAAZVwq0pYXg83LVJ7IdX5c2bLrDyxb9/F8nUwUo/QXddzsQoVYsy0eyYHLwpM5/2kM6Npx9rThTeyWMaspeMz7uF+VglKuKVXtdUtDJnj8E3GISuhFuxnbZ3yRblFclRd/Yu7bjrokOLBxGnyFZjfFGGZk1cBPZwBuV2fOVkrdwVCeM1nrPTaXURoqIMtKPwMywzrx6tdMvJr414qgl0vrgp+5rHVMSv8BT6VaZdMBw+snj/YrgziaO9xzGoyjVnu6KTrd7Vl0HwHjMx9CadO8ac3qkM1oDtY7lEiDLj6UyWI8jn0itVixp38ysybu7+AgffLoI2V2WtIIg/mc0yeMuvlE7w7+rMTHou3heFeTrcGnS2VIBE1UO13TNZPiuMlkXPR3Tj0DUJNoGLaRPFbDOuXCOmZyvuFvCBjAqcsU7lW9348IsUkTcNkpPg/mnhzu021tAlvY4p3l0pyNVNRSGDIz/ENWQUx2JDmKm45CJixf7KIcpsX5neJbUgLjJlIgGIynSEVBWNZnBwpEnypNq/2YxKoo34vcOLjNas7aMs4wsOKGcfyHnJy2d0ILO3VJd/KapuVzG+xz+Gy2bLHn6rsWOFDsi3chOA7X9de704n52vrXdckpJq0Y5+Ft3wwp6JCQGs8vpHvRhX4W+yEdtB7ZZFkFrVbZWMuMu/VGR8Iw7zCQMWtAR167svQq8GlRR+AFlFy12weQIG75uZc02zfVH78lpJLWCsSEOUoEMvDIWgOk449ej/y6UGAx8MOZqswOL9d0BPPy5T6vPe2ilb7lFNP5BvHAylN4GwRTVnRZo/Oxs4L3Ahya6V3Z6HhRbhFOjNxFg8PWcIaiCQwqmsrAZrTNSDiHUFkqiJEICquruhVZ6OD/YZvObXSxIkkJDcc7W/QRR5KNj9yf+V6g5u3qXTvXb2GLE9ENqRcmxSrv/KsUjSJ0zt1MmNQlqCO53EHISu11wQEUPMpyKEwxxX4asqo41YbcAg0Z6Xf1ko5vMb3IP7BgXD3fZ49Pmr6kTPaIgHrefPRv5CMzv7nqgFeRD9Lu3OrnvmXENB8OMwrGQAsM0WQ/tU+CHVRsy9hMKq07DUEys8rCv73Dx3JOsUzOQuP7iNzmkzUr6Z8JrpDZj1nX/b6q3WJRGFU5nzpn2enIPioIa3/jtrpu0oE37WO4CQA3Ro4teDGIYzvgOPYPzEiKtkwFmgYD/JjbGVEv9U0XjnQpc8z6pQLPl1cSbaEXnOBdQSVkHv9YSG+uaHWlT2ir1tubLQ5IXQWam4TgVv+FuSTxCqLlRAa3Q7CM6/RTefB8bveMO5weFOoqYb2/5Tc1eZJ2ojxGpbfWbDfHRy+gsQI7sjKYy09MJ4R/yGUwh4Uhvp1LqwRV8ueSMxz3qRxBFMfpvMSd+VA10Pz1H1Gn02CPBjqrrBMslxeqAn8fKDWGfiIw/4v5eN9wVGOHIOsWNVATUQv6vhxXK/MezArtrOH6/yfWH+a6JgTdLLgkWdd5y1+hdNWyu06dFRR5ngfV+DOlEtgdEAAuZlS6nCZ/OsO63QSWT/MnoUZqn/tKd5F28G44QfdUec5kYzob68mvXXlgkGkLVtJCI4bYEn+nSm7MNtvyBcvb3MfQ499oe8lqeEkyyWIa5bszNm4vOIc80ROzD86K64UNKj/cJJx/SVkYgQBG9glBQtOk1562K40bzNtzyi12EJwK7HShJza7aJzhAhSDcZLfCxNqKbQQkyxsVwUWAMmk44VwRiNXJlwOYuRs9ZwmN0cONrHZpYzvJsjBR7datsg4rnqQamEzQWkzgRfTmjK3CkyaMx0JVulWGTHeKDXsBmqgaPevWV3ZJdupLGdmL8s0BbdU7BeqgTFXxD3aLzgPDsCAygWpGgv3tTup5n5pcPwupI7Y+0gic4F5UQ11BcpLf6sc337J4w99Sla004WUUGK/Ifcne8ep2VPkCSOocQHlVKxPcSjNvduC4sRawb4TzGQIBp7ESwUCTypm/r1BWvgWZyBQvbOw0qYJLvGCSSm1lJPNKOW2d/snuL6osZzDlfxlLtvwD7L2RXZifIRbt9OCThtyGlIv+GXqKb17dMZ0byLpQuj7q9C9Xhlbsb370NKzI6o1LKURYbculY06bvdka2W84sR/43cLMDANSIzev4rza32KkW2BNfU8QAkU3uymPD4Fc34zUfYNCi9+oAj975Z+zWKl3YR6JmzWEq+l+sS9UoBiZh3kQllIrwH0W1e+oBikAnk521HTfil7827DFPkwjcUOnQk+b6yZfiSTkN5X2YXbWMatJuWf23bYoortYfAyMQEiLNHbwupevunJPrkV2uJEMarL0ggechFIdvnyFjWUWMOTkdsYAu45aWmbX+7l49K3NiLCFXeZcOvwNKPShNSBLFY4pX/9q3nwqIZLKi1rxMIfU6qx4HQAbAYg4y9XX+kgV09NsrP06PT4BeG2DBIDZ3A84aRTUdg0Pdr/r21rpL3k/otyiaq3FfsBYoTG9/hf76yHGFSV7GALGI25JRbfyzvfx0W9R8g6qbe8K8VfPUkXfkEi+oFbtzkMrcStryKyCJNoHvhZ2MlyIED+6YqkIGweRh6rnBRy+5uvvblgitdpppn8ry1GdPkbcLQEnV4DbXgvUr5loAL0aZXk9ljdLjJtac3v2mQ6SLi4A9J0ROS5drRngXaIZCEKwZIv0B20YxkBpUD4RjhCb6tGCzaShRA8rBbbqACFQLp+J0aDKvHEuIG7dENnE+J58nvm9Q4R0pnksbF0ENHNzb3+uT2pRy/4n2BFbkVK3qi/bsnY9V7yReXk4Y0zNCAiipigar+WIaBrW4Xn7Y5Le+QwlpiOuxZHnSUVtxcYs+7vbGCrtYb+Wstl009or56pQO3BaNJXURJ7e+D7UVjQageYEh/COd3/EI9IflmCivSxbQfgWOxyh6kKBKWxBa4A+XZSGzOC8LnoFSjSTkkGXGPIliKmrHpVZHhDnZIDC9R3VywVeY/TSgskGiGo3FYy8nN0qIdKI3P7fR/HD0If7g1gOYr2OHRIJEvYfm+hHjpIbSL+XXlmZwjl2pRmw+g8XNeRLtgXZSVeT5mXDtd375YbT8JpdkGgv3J1pY/PACDGOHHGq8pIndzswOsZjPiEPbgxP5Km9jT0Dr3hDQ1kT18KE8ERjpWtVNKxXZ3EuOE6PJm9h+f6Iusxd6d03wFCzsc9F1KPKBd/Xm/wusNq8hvm4wyboHX2u72M2EQPYPaQY316ajfXBitS5ZYwgdxVhee/vDptlY8gryIpKnPuDl7dUjA0nxIJ15FfEaHl/IDUdFOmtMXfjPw3QTx5HqysQnJdrO6t3wSVyhmEAxVzl0fKPcLJizXSKwEHSWcnLm9r3QY5EhQgqjFMrkeBX7apFrVdzq+ENNYWfGZBJt9PaO1pvxoCM0EOqUBB7FhO+Ag5xz0X2U4CLENYvq0qjUNVaqlvsJAvaR1RHRTdIBZNLPPvCn1uFTUiqG6m7L9tIP8k9uEkkfH1Asr+oh1trRqzIPzUTbe6P5CZnheJZ4VZ0TDF+V3ZcrGPUXcEp2sA6m+hmC3H+cYShgDcchFSlT4yhLS4V4OCLZuLRM4J2MP63aYkRw0UpLJgBCtqQVe2CWYVsyYd6fs3hRkh8ChwGpdQd2HdewjE5Qy8zlcSWDtGCfm5WlI
    known_hosts: AgAHjf1D7R1iHybQ/qFVu4pGqNDxcK740lbX4+sJgsA65bKsIwM6NcOaehG0UAsQI6X1nixNTcaTJi3pFb8WsV9WKaxJWFjxeQclsVJZbO6tA4z5TYlw4g3CqklevBr/NdawBLuV/Dea0S/e35T1QIliKqWerntdyqwTrCHSIh3a69ixvKrPMtBQKSvUUg6AhwI7+gvkYnLVitvakI4VtLuqvQyB1A97f6acbM+X4WpZSfSBEvTtcYn1uVkXXGp7yU3w8KEnBW/HiuI7vHbxv5uFFyIxeN2HrakFFe702llIj/YYOlwi8II+/EBuBfHqnxxDHKCd3RJVAnFr993fXdkoD57WEjq8AifXk1AFMSE/cStEopWk2DUh7oqzTRCYEKsIfm+BBsNu34/U2dSmZe5UOIz6IxJIEFQjKKC/ZE4cj3KVnlKbrgeWg3kW489fc7vluYIAe5rmr+uNX2X61L6QHOsQPKcI1l6DwkByVzCXaiQyosyTUD7kcLsoPiXCHE1cX/yKPQwD3UIwwfvfxxNdXXlv2OV5KQUQf0JJFVEwnaVDaWiktnwJWV0dx8HFW8zykPdvg2/BHLjytNzdjzEVkLcWeBOyNtcJj3OcqDmBtWGtwa8j7X3SUBxU7Hwsk27EJDZjzmf5nOprUVVb/TuJbMw4ANwI5uGVXMF1go73SbJKY55NMc42olvJfUF5pb4IIIstGuiNoEhbf/g2FBWSsWGSsPH26fAc0R3aMs3MaKz3lIVuRCJqMGQ0LjSKpyYuImCEyf6VsfGyRtcc52pi7aXdQfOOfyMWbJQdGyErL0lxsCDgv22rI8VBa3J6CR/NaAunSqEUIwtmgJifKzrHEdD3orfKJEWfxtLnprZXmgE/wXm0G3MA7/NIT6f4sR6wNkGeoHTn6mL/dKOB0UbTX/pSoSmp3MsFvGzp/KEPHrmFQzmM3SHROrBGwPG9bOfg9VcUm0FGiLb4WMyWO/i2cjA14epw/89obP+/dAjWjPMzIJe93L07iWDkx6pvOahntglsfjr9frF1VsTPSjnyw3N3nplgfVj2qLgzCgeUyeiaZ/Iko2ygQFfIJtFCc5tvySAKbPVlmWfLV4RR/wawq0um+c5HvsJwRi2Fzmx+/RCrczY6qldsVzGmYvZXm3dR4FvdAtDGLCLkDG4Zlp16lXvptbWniEbkUFiCFxpur27Ff9m6JZ/4jplp+S/3rsPcPTWRLcCfR+Sr3QtnS1VpL/Yq19HexCF26k8NzLY65lGtbGGovxma7tnIPSodUJdhitTHcRwgNFymuIMbdfdYFdvk02g2ipAge9SUKMRJiRPUQNsILa7TSII4s9bujJE+iGUfSq53E4hPAOZvccqvUEy+xMmKlPRLLmWFN9XB484bVCfU9vy0co0KDZm6v2ksE4BjnfOekrXMtJVMN/hPTrfYFn5NqdqqTBNqTiJFJgyodCtBL+RdwVwux7DoLEaXBNcxC1vVm03MtI8JS4durDciR+u00hJU02Onxb51KdsM2/GM4Lyhi7ZgCm/02QRuaFBtp+s7zKkRG2iLT/G3T04FLkyjcbGDWXRXNBKUl77DJx+WhzIMqtFSa9kZDn6FZ4wg/hg+p5J/+eIFTZencAA/98Jgr4Rtt2bM06STLhLL46E+qtbmAMD4UVhJ0XPoDfbDhsErAhrS/VNRIfl7fy4+5tWjen4j5fKeGScZlG35uV+AzaDLz/DKg0yYT6kNFJsLLpjbUKeoz32RIWB02uO/iEwJwqQSDcr7rtwrVnIShMycOIju+KlxDhXHbfmtLgT8jWVKKUnb/+w=
  template:
    metadata:
      creationTimestamp: null
      name: github-inkture
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-inkture
  url: ssh://git@github.com/garugaru/inkture.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: inkture
  validation: client
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-inkture
  namespace: inkture
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      name: inkture
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: inkture
spec:
  encryptedData:
    token: AgAkAg0yCDYvwKPa5GFJOXXIxTRVyDeTaKDi15mGUIinSShQIQLxQ5kXwUvFFK9q4KDDym+B2jNLB2LTJGDaelvmjAb0HQ78DoOUK82viOv4uBeqa/HuUznkm1N2Mf26VrwRC22dV2v83A3jvwfVec0JAgpwu8Y9TPyxUVyQ7oEpXupCq4688BY6Uy/RaRkuc8utMXq6oYbW27DYDE6KFrpQ4zz6s6DK26BAO3S4VNfwPLWfqDBpKtzE5yManBm4mdsDJZc/9HmqWMsHOv4WSKp1sPQ/HgPtsrnPU0fC/tRun4Fm+sIqS02WduxtazqSUmiWtDL5cnHeeUQnWx1iabwRxjL6K6yQIL2geeetTIKWdUaGjKxeqhGcuzjNr54Vi8RVquU828qEJHEW3C33VKddRechul0IMdipYFEJsQqHSXvzcHCT28A2cPOVnDrR42xaG1sLtvz5bvog4GiM4Lv7dQXQzEUvAo4DYU1Syyn5wYC56JKwzqZ/49f3rhbXS8MCjDPLccxpLLdJUrRqoLaT4YsNbQvO1E03aK/3ggkOeLku7d198RJJU1KDpsJURiUK5mOx4z3ZDaJKsTBbMM0pTZr9PY6YSuKeqX6E0p4DySQOS5IA/1GzrIZe+A7mBWbj8Z2MHR1MBTPMQWHclLOx70ac0vSGfofRgVYaPp3CVs0Ei6S3eo0Dwf/snn5VLLw9bhr3gZsbPGXnaPbPHWS42AiJnK4gJuikeqw/rSxPYdaI0eCiPw==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
---