---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home
  namespace: adguard-home
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dns.garu.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adguard-home-dns-tcp
                port:
                  number: 53
  tls:
    - hosts:
        - adguard-home.garu.io
      secretName: adguard-home-tls

