apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAIBTXDxn7bp/R1o0DXZxCcHqlSP8U4he5dYE9WbaQF6e2dtgWNDp7uUHpRF1V7tgvpwp7csK8uwSJCLVuNNbc5+soJ5RQumBK1OWyuWkXZSw+O9QBxuu7KTV24gKx3gabyh8PozuwTVIt6KzWWBiiWLUJEHN6ozG9UbzIixde2QcnJsOH/MruJT3mjk02mw6IxS8//qzNsz+maI1k2ZebWwmDbztXMJyNx5Guk4p9EpnMdrSoUSwqzz6Dz13UTRRSumXeS+2zkkSno9XTaZtXJzOGuvK7DtPFCDeFVs67HQJqk5tuoLRvzHkh7xTgfSsu4QfmmtOLUVQ/kNV3h3tLgvggwfHLKYAlfJuDsFRz/bBvkewwiYCbxMAYuk8j8q/9eYZPK1tTB0MeCRvVZyL3xytpG1Zqow6i3Cr/cI92Ft9/RIJw5Yt521A804MtX1YuJL4fL2k0opBw81ICl0ivbdnrkynvp0IyNZ5SxBrFal4y1tg20B5TDX3PUmbUoK42RqyB1fxVR2pV+dObLGdMhSScceM/s64T6bTuR5LQrD7iC1Wlt1zeVUZFvx3rJ2tvU+YsY/LLOyDoWvlbKSOmaOzB1NjkGjFT9fI+90cPNSP2fPsbe6FIR4w3OP7mBv98y/D8zqEXb2WOQ+6F4jlq8UVDw8cam/VInf2MsG9VRRc2FBuoqL5gHQU9zQW2V1dJg2krEJuMDX7yD1SyDNg==
    rootUser: AgBVl72mPnaa9ME4paXXc21n95lPT4ZwiLURCO0qMC6TO7hVFb6XUC+W4vTvmwFNsfxhFDUH2rebAITRNutHHBtGZXg9dh5QRo1DeuEA9wFbatfUCFfncnYQ89+NGKVCVhDSr/jYV8O/e+lVcdWpmTcFmuphyve4e/F2or14FvMuu1DSIu2VTfb/DQG29T0vPV0SItOIgNu03wXswO78pIB6fD2xoEPPaSaOwVMlPFjGDKMQ2Rd3xHBgs32ryZix4lTBcBAbr37lK2dwTZgawCd04LIFev/JpnrN5cuzxY6OAoDrePN18XHCV0FT+/H+nMYnpC8SidK3k+eKT+3FYUkMe1K1PSfCgU+b9ZLEw4+AAd+uuFlvEGiOetfkaZAfoPLiH+3k0rB+23o9y7o/FH4rVbN876kF5SxAlQI5WtDjuK1zK7Crar1fPm+9DCYqnF8T0KLCtxtSTKnnwB7Y5yHLKMq2cuTw/qU+AHMWbIl4ugsi7UKiqUYYEGxV7opR8w/KZxujCAmTzJD4IPm1KY+04k6U3Z4HJYMxkbgkvzs9ySUfxDvZbo4MXM/uTh5aBkOeZKXWUsFxl7sDNE7Yx2X1Of4U7P/Sx79qlKmzv/ULGyLdzMH8jpLxBkPgUDKwq74JWG5Xzop3GS+Y9S38Ai8LVI2cMIhiGZOjn/noQzgU5IXUIb54nMlyKS+C7RmYQh9jjJ+Yrdye0azl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
    type: Opaque

