---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgDNbk1JhNYEwi4Ymw5sqvS+S2ZQ2+Ra79W7KVqEK79EdoagrY4kkUUKEQuJlr+f5d6DzfPeT+ElzNN9G5+67sEuH5VWnoIXlzwx4wsMpP9he+U98slHZus9fgcungEqK6jQSaZbTbcb1Aghifdz2GoGSad38U5o62OijpH6xgEanVfWRBabAFUwqiq9qJ+TYel01gyBLln4ubnJZG6lnRcaczI7dZa64N0zKXFABx9VuJVCnl8ajolE3sVzUawOwvL7a6j4lUQPc0N7pow5Q7wSNd/BTxx+oXqoQfP0Gmul6GbpQtN5mrD8TaxZxEqR/ykFnBCrZCKH7NtQpG08XPYSerZNEFbIoBOUbm4RzeE36yVaZ+PPmF27l4S4ef2+RQShp55APvvYQWwbQH/HLb73I0g6waIFcSHo8d5NHA9W+qPU8Dcpdrbt5vwmRwLWVhPmV4+/2pTqHVI8dgYp6pfH8aQ24XZK051OYAe0FocK0Qnk5NiSPP9626JY/DELM8/4x+JvZHWSFp5rBpu4TAFSKTmZaKTqBaWRIWD4j6N+lMEf+eo3IxROs2J9xe4g7dlkp/uJ7tWZO96NM/1liRbZ0oKNiejMlI2wGaqltST24WHGtwvEm2P2KT0CLrA4RwMrHPRuR/yp+Ji0lkPZ0BnomE3lGPwjWY7JWUNr14ovnjCJrtG0K1b40s2wcrOYiCzxeWQW5ZzH9IDl/HNQvw==
    rootUser: AgAzzws4fa5fm6nbWyPjBH6XDjT6vpJRRcuoI6obWujq7yB5jVzGFREM4OtzIr+Z0wrC299yXjLSPzmn14M1xyBzagqpowHB0P5gTHQKEmYGTiG0ANqCeWgXrNHVnuFJvyuY1XiIaF11UZA1iNq92fQNxt9ZgdiTwDEFG6cDgO5Ew9xIp3fRErBr1sw4TSUaU3wsqrlITu9aKvhNe/fAHPzw0rY1W45yZXex65I+/JJcMWsjbU+S1ZOfmegcMp2q9o6rlZ+3+kFwxJdjQiqYGS2IYe91ua1njQ6qLRDP2txTDtBcPgt98ze2/TIJBqLgRk8xEJ0jpUtflcDiWnucoLkFCVgODYVQzbAYplJUPxLwH328lLa2h2RLsSt24V7TruatHOCyEHiSXBJCEPzNaLCDH/4blxqhHeS96nBv87ETxrHCdkRax1a3GOnv4b57wZ1GRUWzwnG1fG6UMYdwAIy6ss14pIW5nWOU2ys6kRHOCNqMfOU7hC6wwyuNf6yGD9rJdohumPPbEPQviR1JQ0t2vb6oA0tCIgnOL0HQAbpzUhosv57aaJY8JlCg4hQb0poSLkF+dMScoyqG1u+nHc9QAm4J66gSqfncBGOdacGeMcRP+efN2dw0Pl46LKizSAuxVAX8iW23ESZ4D7uHgZQdj5uxlB59jBCn21pFre05eRWA32IWl4OfVK2WPxSGfKxCk36T7X2VEDRl
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: minio-credentials
      namespace: minio
    type: Opaque
---
