---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-operator
  namespace: jaeger-operator
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://jaegertracing.github.io/helm-charts
      chart: jaeger-operator
      version: 2.30.0
      sourceRef:
        kind: HelmRepository
        name: jaeger
        namespace: flux-system
      interval: 10m
  values:
    rbac:
      create: true
      clusterRole: true


  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
---
