---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: jaeger
  namespace: flux-system
spec:
  interval: 24h
  url: https://jaegertracing.github.io/helm-charts
  timeout: 3m
---
