---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dydns
  namespace: dydns
spec:
  selector:
    matchLabels:
      app: dydns

  template:
    metadata:
      labels:
        app: dydns

    spec:
      containers:
        - name: dydns
          image: garugaru/dydns:arm
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: dydns
          resources:
            requests:
              memory: "15Mi"
              cpu: "50m"
            limits:
              memory: "15Mi"
              cpu: "50m"
