---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-api-token
  namespace: hass
spec:
  encryptedData:
    token: AgANkMAoyMv7cjYZsybhs8br7fx10mCyGF3MFX4W1usmbsiN5UDFXVwya3PhKOTDeTR3QvwwBE7a6bXagHTlWsxeLLjXTgs+L190Ex2zC1f2etxWpplkY94nZbl9E3dWsXPuOX7sz/10PHGzrRjSpzKaEF/8YIjq3PiUpndvhTbq7w4ANjbRjBLwwERR1aJQNaU/SwBfVhztaafoxescqstxUnBDCGNZ1dS2xT9GXlTA6EUfQJThSiWb6XLRNtPiWmQ2kjs7rhq03t9Oj2yr3KDH2I8IB03gbuM3gcvEESVZDuOKI//hJwFmB0Oq5Q8EWYVxKO3uTbWftq/QcWAWAZxN1kuL0Qaq6RvraDl2xVnoooDnsbwTMX40ORCcpiVQbjKmN+xs/kwH1Qc1o6TuN5AH7v7nb7qO+/aKu5HqcLIOV2uXjl7v7fWaU2qxorBv9cnPpiDvwuvjLt6exwOtiItVdSDWiLV41r42DsbHbOFoUOUWdcOAJa/EAjJ9UL4df1eqSin5T6AvgJBhNsJO3lSteD0n6+shVY0UWXtp+jXvtj31vZJPCrEjV7m/wgex6ujVsNWXPWnYtImVqvfLG0srBPBLT76joSNRZG0rSH9i9Llq3UPMSOxGegzxS6LfYTgbeyQil+66bR2O90u2rg/nMoRL80ydRmH70n40uILHPDl2bkidiulgCvsafqH9/Rx0rR5C+hAC+h8RWqm0jttE+lpY0bhOOfpFxLSDPsp2rtbsmXvlq5aNo+JWQQn1xNgUv2WMYAnks+ZFrVZpAFi58kZJHqQeY/CCYhDKroVcVmDm0PC5ZvFuiXx/2yYRNU5EcdrO5h1h1CFAP33aVWaHAo/EskBQKLqmwfcqIjm5gjSin3AYeOmeeQQpb4HIVBSKQs9j9/K0qLfxB4j02MeZ8Clc8IdXX9ld+Jyfer2rrPp2BQTAv7M=
  template:
    metadata:
      creationTimestamp: null
      name: hass-api-token
      namespace: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
  namespace: hass
spec:
  endpoints:
    - authorization:
        credentials:
          key: token
          name: hass-api-token
          optional: false
      port: http
      path: /api/prometheus
      interval: 60s
  namespaceSelector:
    matchNames:
      - hass
  selector:
    matchLabels:
      app: hass
---
