---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-api-token
  namespace: hass
spec:
  encryptedData:
    token: AgBtcfFoBTqzIETL1Z2yDaMAruyVsiirU1yKU4XstEOFMVl7pWgiDJOjsNmcR7fkDOsPP9ZZyyS41BSO6ni50p1pxDSvJyE5wZRBuPH/EXkQuvA09dEzwrWqmex3R66CrqwCgMTcU1uMkf/PoH8G7FtrM4XmE31GFWGFTrrjUoIM4UBEVhLqG/6isivRLQAYFm9gzT9NDMal5BlPgq+rKWHehVUr6+ouBm+M6u/wZGHizoIJYkfyotNTbh9Xs+0+ilrzDKDNxQUEC449tG0JJKil8iylkxlEXZxzoi0stvjO0lceD/A0ZkYRienXoLSl6nz3ADLX1wpQuRSPl5LVB1bV+uCWftG7QZPNiSO2vy8BVMXTfsJVKZdfmObhkIUyzOalohc+k1rHfX/yWSxylqf5G9lsTpFGIzRi2nZ+Y6YT8X7+s62e1z4K2QN0uZhHASzksJbu3C4smMJTF7UyR98prNwSHKCIchrH2L+SBn7PSJqxdhd9S76ckhwFQWuiqA3cJpnMZkT1D1SUUOvYFT1IR+y4a4TO8ZnqgAhHSMGcgNHzhLZwbEJBuqQ/DkoWcMmfwpserpvf62GHuGGYXrlY72rdLCuLBLOoSUP+H9QhNaM0cNkj1rIbSgtGZwPotjRFCCzp3WFIiTwfSAv4F5bMly+59CihNHEkKx8YkMhOZn9dXtiF3ZftdS+FmAfsLtC4lHuLwr2k+d2QlguYHrxRjLxbYKYTDFjzacep/l1XFEG9Ed4LVr8QV288
  template:
    metadata:
      creationTimestamp: null
      name: hass-api-token
      namespace: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
  namespace: hass
spec:
  endpoints:
    - authorization:
        credentials:
          key: token
          name: hass-api-token
          optional: false
      port: http
      path: /api/prometheus
      interval: 60s
  namespaceSelector:
    matchNames:
      - hass
  selector:
    matchLabels:
      app: hass
---
