---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  encryptedData:
    identity: AgBgWpibe00TycRcJtuOLSah85zfaPQGy0aoT5dYBcJZwbwUqOTyg6tuGoXJ8Hs9+QEia6Ug7aJqKaQD9fFKdG0oOJIiQ/omSJt/S611DjwHJBdintoxeDJikBOhZzLg9NbcmS9H/2tHhJKNqYxCJCZ1kgjF9TA0ftEwMQooOkjZ8Y7Yn7g2Vr7NQ0+y8M3kDfezIJWZ5Tlt74jmhgu15kBxCJ6/87pj5zwBscpFC0sOXzNwBw+Ng6eBPXp+uqC4a19VxDcoZeVy54KynykHel6PKOmrGXcK62Fv6xaF3rBB/YBvtIYuhJr9vhyIMnYwcI1V8wPLp8wnoTymdy1DQqpCW0Lz/xfEpEqPpySKPuDYibCBJobFAMzVXn1xRFM0x8QxhVYrRrsc67zrzoOUiL+Am/1qRTH+EOZhGKFofm62VNYjmp/ofadB/b3GYqDyWz1R3JxyZyO7SeE47fjLgAbd3tZc/zD9LllclFtxWpjGxxPYLx6sZvkA6P5XNNRGMqbVpsjRWvr6yz1xQNTIKRjASB6Eijy7yQrwYqIiktZcPuvcVweMXk+x6p0fnrbOmq7LdGf9lz/mRdcRhQkoUIX3nv4qludkqfgdAWcXaHNWAqlOAOCEuydU+vSvUWUJP9m7cmcDcgGk3Nln946PeC1xY5ICDZm3BJL5k64moAgGQpC7hNYlbSBmyTow6vEguFjrYWExBUrmK8QHy7eva2kY1svbPjyq/eNz0bUraaVcsWtHjO6WhHyfaC55RAxQBlUW74nGz4HFxjJMr6DOUCEx0YvRUPeEPHqksHDVnpSwFbQFNkBUwjxm2Aw7YRaPEWd6PXo7bet4pfwzGwJW+ejNdT47Rs/qgXRC0JBAXoGlrQsVd62zOnhscHNdCcpgsYM1oScSYb1ic4H8c3DY/BZS4G1+p1NA/gqHUjsWyq/N9Wez77EmwHRW0OsLXs/oVv0AODBLsOtSgdAP1PLI5kVXqfHaesJfnNxMTJBwmllBOzFxQQ==
    known_hosts: AgB+oUEnSeL3oynKBZJQHHBYgHdTxOMI3487eXBl13Dgn3NfWS+B7gcb3/qs5kFWj18hcy1K1aXdhgcZK8YbnQ79JWAL+Kk2Upa4qrv5ynNP3VQHjo1PZIVnVQFuKoZrCbq757h/j6pNY1ylAnL/zaqKnzagtNdZbO0ShvsiBBH0wlLTC8VMxF7IU/s8unefDuFS/cDE5ixJ/+bjv6aY9jKReiT9iLIfooxRXZTluRdz+yszozlE4Zn2flU0n/Ic1UtXEEKINYfeuj8536UlfWlayMmqFRCOUjRaE7LWnxPj7w/KjBlltKuvuW1y03dUPr9tXp0mO+Y36ytpcgS5+fi2dvgbL4xETv41fZpd6wAl0vOh5TX51gLqHRNP3RIrG3H9m3hoVWcLA5elbrVfjJ5FMu37rxE8jOFRmDMzYaeVgGmBoGUR6T4vjaEXHp5cQ3U5/Xkl2ZZKSqj7wO4QaYdhBwI0gRtLFO3de62Tjrqh6OrM24E/0Cdl+4MqukQJNnGP4HQkOQ8YfyB9Zu+0UjHNnjJz4Tm+N3mvJNcwOf9Dmw0TRzuGjeApUNJHayc9w3WRmBIzw0vOZ+ZLpVax9+Oy1ORaH3rF6zv4t+XOh4KXK0QR+cn7hYbnyVcTRHEZeXDYj8q1twH5DQAG+opI908ihjOmiQDJs0JZbsATz76CHO1pLo5/jPGyptFRPSTYDjOCHqUJTreJLo8D7XxjbiMk/C6BDk6HWSAKFTvzmzMG/JGFegu7K4EsPjbuoln5NbbtbFkvd4QNnw3fgmKAkswlETvKwPZiQ7VKOm9E08FmZcDScKXCp/wALLhBw/nlmR2XDj21X6lmrfzZYKy/y4OqvNd1w0C6KbgPgkRiQwnhhBHbw47AmhkNLJ6jUwZp+TqXkxKdGpoyDGvN76WZDOfWJvuH35s41jjA+BE=
  template:
    metadata:
      name: github-imprunetapp
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-imprunetapp
  url: ssh://git@github.com/garugaru/imprunetapp.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: imprunetapp
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: imprunetapp
---
