---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-imprunetapp
  namespace: flux-system
spec:
  encryptedData:
    identity: AgCSHud23CXSMvksOkfu9ZLVrvF/vnDhHOSQxbxNZr/Bi1QlQChDyubpXwM1u2ga18dklEbBtVsz2E6lyGYSNqwsa3sKSMu8wcyN/Yu7EgkpVVES4GQ71ED9xb3XJWoDqT++8ILyxtYyOTy7xHTTo8ryz258ctTQDCpUIFY40tg7xJUclj38JoruXNehudHRJGFfrHTbyeRsjXfenSQmdSVU0rO2TMjbfT1KGZ1Qzz2jc71j8zPeD5hOvtccjHC2zFpRljiZeTteGcNwnUMaPLvr6xLqouUVp0Ai4QHhLg0IuYBsrnxoNtzcX9y6w98bELK3R3UYIDa4sobBwmNbjs9ECkvR+w6Xta3EtNxyzc3p7o4Z5ZdDqe//ZrZwJ7ahew7F21yxmu8G/QOAZ/2jDUN35PCg6VW7qqiYGLopLYiXX+CTWFt7111W6UU1r9W8RnduZsyWT4Q9h6GtzIyKDRX6dUB5ARhJ2NjId6j3SGhDtMVlu/1aUkHLA/ykI76S6mAQdfNgPi/nv5i8r3CJmeKtC64M61hwocsIgQ3qfejKB96/ajVfBB6yYQtPilFKdq5NW3QKVTz0cZzlwz9ucHJxpXwg2BqELoELDzBYbLOV/AZJ5W54gHoNE+U9FLE+CrFs/ke7u/Z6KXOYMEmVdCHOTAnmyGAl4ZrlYBPCElJp4AChED2AA2CslwZTrCShWiItoWxFTl4EFwugoRHXVDEypykIb1hZmZJ+w1b5DoQwq9JNOiRq6DD/mIpQnju6rXIf4vO1FAnlMbH0JX7ljmVRVor/sOZEso5QXNppRSo+g47T2xOmRMiq2SMHAugzRP8SEq8N0kxOQDejyxc9NCxbUvNN7b/r006uo7VqLQGBEn04s7r9pEcnW6lzVJuCqDRniNOSluyrtA9lkOpAmhhSXuRt7G+vuu8pM4IRxcuHjjz7dkTsNbTjHnSb2IMSvzeouNrkC4kxDc/FE4neYdHlF89E8dLUwrbElx9UCf2WaO2cWg==
    known_hosts: AgBjPHaFHahtsG00IAWQwC/HEzrnufBllIfSyd5IFhEwWLMW6RXjO8ab0MMnKoXh/YvPrFxUFBazpjX/TfPsx7v3uaCmEwy16uVwEjfCoYhFIXj5JryV43C731XVyju8C1NFXp9nuiueO71keV9fvWo1TK3vo8Xx5Wf2PStJWtEBk2SsVFtZKZjWSF6tol2xP6vO/PsBDdodKXqqe26BdWl2snhp4KDxlvlk+AUQd2tcHEKm2n8XfbZkV4gXoOFqvQCv7Byq/Z3hbSqfPI4yEQ3wrcOo91j85MWnAaC9Nz6DT2LtTmtTC5uV1j+Fnn0P7hulTo4ldGrop1JyOw6tvkDBUzqEBOCObrqNsGZ2O8izDyLH6A6pzPIWOOEi81ycKS2FvHWqMAB6EXfau6libf9LH2319B7o6i6KSm/jTOoaXm4gYCBFW2oF4G4N4R1lqsDfuAJP4oBQH4vchgkreAbMhXuauRETMxt+LrUABcCz+xCD2WLw7wR2AUKC560uXOaoMV2gTXVBmrg/rmc6zKrQq61SGbGCndeNCPVzGpdCpfAW5ePQqUTxxR5tvs+Hg/m5G3UzpzKKNAmEt1ILjrvJpcM2M82Qqq5AyR5KiYEgWODDb0vgQjrAIJKcJgZAoMs8ee4G/xTwFkjIXthTrpba1rvmwM/R6KxRmD0ss2JdeKp1njQmsfwJ4wM7tyaUtKD9ijabI97xxdQrFfREb4amktOoh0TIRkCF1E2wHj/Iqgzdtx1Ij9sQX30L21fwH4Rvhd/W7LQCzm4ow/JFCsiLS27mDiX22MKT5RNQp4Fan4xsF9jxQ4xBjqaCxRnm6f7Jo+meu2h4NZSK35hYHSgCYwKDHkPMTgCHq6dXTGnIUlYtV5amXY6TRcUXLCH6RdgySrAEwRY0Aym4Sszt1k4Pr/j3I2zl6UAelPs=
  template:
    metadata:
      creationTimestamp: null
      name: github-imprunetapp
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-imprunetapp
  url: ssh://git@github.com/garugaru/imprunetapp.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: imprunetapp
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      name: imprunetapp
---
