---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-imprunetapp
  namespace: flux-system
spec:
  encryptedData:
    identity: AgCetfBmXRacDIOxVJWNxsEO8fGq2PELdW5I6zIlSwlRyFl3tpcKNOaM2TYEqkKw9y9lduxHARIYozrFOuVWl0NHM0HA0eX/XvJmb7uWGua9D/g75bQ78GksEA8HhIhxRfcPM6eXGKfzJp1dLnBsXlrvLYnT4P42HMETxiYbZk/V5nT2HHRCTWK2M8d7kpVmL8zuYvchVin5wHv7UylEbuk4utawFzRoc8dRMfWWJ5rnB9WRjKNbwudAHbajEraOR9Zz8n5udS4RXJeMG8HjnQ12H+NrIgM3I8kyl5HFq2xPgGMkN0/M7nheDFk8NKAAQjqom7adjd3P3u3mE/XAZCDuinjOIL23wbOJkAdBunC7QemlAEOikdCIJq85OpLyrHmjIs2fQeEF/NRZxdJYQjNLok77AYqPGoh/moaTKvcl8VttGL3KqC396vx09KV7bIkj29+0sogCCIIP0fOc4TwapQHr4/8kWYshz6mTvsldi0WtWQCKdX3FwNssheyFGYDucvLdPBcvDGbMvqByaxh7AWKyDpIbINg/m/bPf4729oKNxjECdlLvV7bVdMFs19RkU6ddzBWX62IGnGgOIFWa2LVPVxsvoR5z2C5YZtio8P2msXJ8WJkLE6mbLxHV/EIWdmUgHaTOidfOimIojkkP9ZvuZX3U//bmuZbhMjymhID6PkfTmvGugJ4d+kjOqjSmxVOzHBP9XSJii4oadkCTUIXJwiYkgHgwAe3h8kq3BSaXvio2nyA0tqeTEhSuCKMvH0Xw/dGm9u9w8GZN0mkizvi70oFrKvBBViyaadQNxGs0IjGaQ3HN524nTHGpgvsO2TcqJJzwkbiehfz1jvKG21qVXAmfjHp03hq5LYGe2FREcobjyFQP9KTJsLRM4H+/yjPh070vnrP+AcOtLjmI6YeoWTxjPdPM3SJO2rdcXpBqFxq5iMerEP9/TW0C7TNZZVQpDgjXde/8Orys5ZrsLrZT7nxV6gLEINopWRLuN1OTEsL0AZgdtInbl8PbUpX3iFbENv+bkvMAUnBh1ZIlmLXc6vO5NIm6Q/V+D9SZANDevq5N2P+WxzTxUw4yv4Vx6WRr9wUELJLgbaFblhw9uyoLdd+1zhu8Ec54v11x4V76gH5StZwJDwdQvSE3F9cDDIRFOEziBdg5SAaIQ6wSvZWNU1Xl7nGMT+LVD9FNlKNohghg4JWQRsOCeJ43G/EaZwBeDV6uwSQVIatOf5a2kvNQefxJrs8cWTNUfLlH7HTCrQb36YTvfxvzQSe9KiBPqutW2cb6/yqnbJs6pLQLqBkb47+c2XXwben+MHszx8z68sUHjm3J/B0k08UG2sdr+tBJPBAy57FBuxd6ACWXoWcTpBMtUdEIrVrr4pMGrH7/nq9f0KYWDgIFdSvJ6e8b+40cRT8pUmECODKASl0qOUKcxYedapV+6XhRst/nrZ3kSCazygADKR6KaZBw3OAjTS24JFCMDfVM9xsmIYYmUGf6Dda2F6JrPUte3jajT/tui+T6uo5fJU0DRfqnLTnfQjnXps8lEYK99GZsy+3pEmnoO8tpnD/lp7Ahtpjry2XEkDH50viBMQ9Ns4qI/NbdiwtZyE8EvG05As7emUX1LNojcXfCB0uNsguOy16//A15gA578gW3Jem6PhuV9NpExe8FxzzQ6JXUE5fKIFZ6D2bs0KtA+nbJ64Sh/3AY6jH9Re4f9knVP2Gh3vKqUvfLoslCjRaneqvg3ujf+t4G76wRUzwyivuHtU7EZxfk59pKHqcS+QvLRAaMs49S33FxyqdbAAg4kOTHLuVs/+ttkLyiXPUdbQC7d3cTEtdVPtKAzEwp6iHOeoD78Djxlgc3ke7WPZ2g6W8D7G8U+ILZ+GQqXPDtNn6c6t7Pv0TPI/GcO3OSH/+nngvK3avRRLuCTX9VT4K3KIPGaEPklzX+tw0z5TfxfFF2AZPxx3XvijQwIo9saHC7xtQpFoEcHJOqSpVqDlYwabRYeRVwxDjZyIYyfjK+C/CFdVrB9voeH5nJx89sF1/tRVI32FtyPlvfdorniCgQ7fZfVxlohaaOMJP1mS6SLI557P2/xwqKU9lcY4h53mdclEnngUlxqIOUFNDZwCdRMm+iHKbRWweScN6F8Wv2tvCb5aF2KoF+ui6O7+kAASsjxXUuajHvssmd/DutTAlA/ZTPegvgTvLvs/o/t7U7nhXmupHQEbsagHiIBr3g8t96uXfrnO9L8JW39YQX7JcoV+uOOqfKQRwA+jMfRnWXtFODrn+NpAlZcIgcURRyI6K0jndqXGOik8nj8E1abf0wVe8uBZ5PE8fiPVSfvBZpJKSvvnU9KU2bRc+gCSSj/DHB3oMuqoZMxT8jf3BvQAXaL6TQfRinYn0Iggjwgi5tDRjheVrDuxlXVlRItezo3PHtL5RnRt4YAz5bE7PPJAR+tof97G2buNlPw4+5gOstl9cCVmhU/hXbHhLtJjckGPG1ckekD1mBt/O12eOYyuCXS6ZjUzhTURnTwBWxZdGjAI+rjyPbTI4naAL5RiS3vO9REyRLYuCfWYN9UK5dMDx2IPq0C6pxcUDthVkcFbjvQnwIOOPM9RdZROAmLTi5hePiHcCEFGW8svIrQyrWBuIB46/8DEi7FrLj1oP/67ToEFwvjMKJsOvTI/zgp9XvkNGLKtLlbiZvWoLuaYtZ/mpKAEpfAYby8mJm1yUIpFpBwn5hrOC+rTNV9bx1z2iodYOFmKJ1qRxqQ+OPbkLRcLixOG92nPac1PEDhrbiOkbcE2AVw5TkeHJ2C7nCPq17uSpIswUPzf4Vrkgi0sX6EpowDh3ehYaBwL9yGp+Sx5RJimkSBJQLsK3Bv2LirGH3wAtdn0ypTHAf/7Gmk8IYzZDOOgKxFoYnZZGKCei1YrpvJPnVJuAKTN75vSOA5q623j6vj2c7I24MTvWdO0NcCpPGc75L8ktWrfdTsuZod0mRTIuAZOHX/nOxDMZJqcjNoeL0s4nXoSNT/UnaanuA0sAl/00PLLZKdAFnnUQ3hqJBEsa0Eweyay+y5gkZ721fgSNC/8p+5K8I02UlCF69AqPJUEtF/8qXPRp9aIFyEeVLb+qkXnehyLbzJ9rFBsFdWCRmjlTr4ibsdOlXIh0hoDHYpDetWk/j3asC0jvi3pm/tQCk0K9jNF+5IxwnKOzw+25u5Yr9jbMSw1MdAOGULRJsqgyylApZzkA3oalKtfgi78eqllv6toTRXZnU6CVAybU2sd4xm4KTxwWoqTFJ6G738tztoOZ4fuP+GkEuqneImw5Kge+rXbMxJfgKtRPS+R0vKMpVo3WkKGetDqDUKja9V1d/SVWxkscjGOfVKOzC+mi+5nLDXWk6piTqlQnCd0sMZZ52dgLR+jGu1xAzeYPxQiDAv7fsQGUUbFLKj25vmU/nZZT05kqhUTsV5XGiclvu+DvInQcePbPY8MnJDw5FMIvWUHoAoQIDivyIxpu8CjW4IB9x3ML/9onDl1H9/rn6BwRpWLzjZJt3PWA663EoQTcu1XkDeANRDRSg9PT0Z+nQ7HB25Xwfk0yqqJdwVB7kf3D8kr1B7823boSI5sbKeM/7hkZcIf1+/x4UWGYA/Zg/XdvoeY6/9Yj3+fweoqmJs/IsCvY8PPk+jZqHKu/O0taksWDSkidIJyddHMbc0FX7fX1EbdlyX8GgO9/3wXjFPt1oDJO3XnYFMp8e7g0xvvhuZqAd6GiobXJ1CsT8d4Eqi4QmWni0rFkwna/I2021ZuPDsHR0wkUMFi+GtYxQ3xIlXWNlY4QyJiPT5q6aQWvNtcDB6JuYVH4IVCn4vLo/nhRfj+fFOOUOPIJsuIboYqezdgX3gS5T5m91RphK49GUZ9fHlgiqVdDSBK4BZjfr/MlXNtITMpNC4xyI+VtApanwRaq6VRGHk9bMhlqJ4+7eZtlgTjtswiTdc9NgTrT2yAcqafPPRJdxGQy5/Ea3kgkO+kvp9ip25VP1ifstoy2lZIPnLINf38AOXUaZmc0m+7Sg/2M2vdXb4ug7G13AUlGu5GYyfVrUMK6ia9lUBtTpt2xJUyOGHzWJa0Np4BYH8arSGk0sPBvXBAxuwaHjPOvqkliEUqmAIHQzPfNMYdh0shnH+2vzlWYIN09Uvx5+gFJN8bVf3Jl8xhqNbo3rS1OX
    known_hosts: AgAdoUc5ZSh/LEp17u5eQHayidhSqOHb9DvY7v7sVSr7AwfpqFm/XTKxRQKIP+rOGupbbywXoG6pwR5s/5e5dLb/7hDcJ++iRduWtI5MdX8K/6Hx/i50f6/y3syRGInNSqALJCdrATqkNDE1B2CWtVYaNdkMMN7h4lDnpetXmyvZOLg12hjIr7jyYbizcDhUgMrZvBg9cEBanyD23IA8J32cU3My6ObXA1PaxGN9yOI+5VUjKADgKz3Z91BJUstmyc+n8f3beCQvKEtWosm0yYdJkeaEpaWJoOwAD3TRk1lBaUUtoETwEfM7kPZgOZqou9DovgFURDyLF0+63fxGlo9u2Y9fiL5Nfp4KNetbAfUUnlcNy8CvZIYsl1lO76Nevq8+YrQnEow5BH7P0vHDVVKZa1n19crlvr6ru7k0Jnyv40FGCd7j/9vGqy6k8FoSxoufngLeZ1IU9lfqSoccajENXtRDpZ2iX5PY6eaGjS13p6p+ZBUdN4AOv3G6g5i2e2DLKMbhJyTvHJFqhxyH7dkkXQKEMZPw6Rqwo3J7qrpzVRA3Y5+OK3XOgfuSzk8ax6GnS1STljqQoXzjmm5m9sxFifFngK4vHwXWEeBZMUfQVSndgZ1oQzL50JkpmshidGTX1WO17Rwv1iY8uLyfc1aFx4Z4Bo7QEgsJAVHrAoKVFmJN5bP6ao43UTIRwgwjMCTOXLqzOrAHSezzrtcIqzFG0zU7T4rSQVFZcVkd1j+Ea9YLsGigFyL1dIEUMq8DRtrP7LReDgkhudhsSI/5xZkH7S8+m3ZOJsxVTXOlleNiPr0keAjOzKd4tnc+Ea/v5QQGO5T8SYf8vm3JwEtioaGGbkVK/zpJ2I9MJBm7ZmtZkNUSpLTyntctpfLE2CXqifPaMMqqgSzUhNpmXucRHonD76tYHErND8qz+71LfCXIpHNfUMk6KaxrNB1MkmG2+8OlJrRBCfSvZRbr6l4iRN9fi8AgfpSh/YxaVmxj2a18Gwi2gyTmSfnHYeLuOIlnXUDDEhrBryFmDlpNDJqbnUNvlczFqpXVNlOTvZy+flaKBvHmAUmDe5KlDm0emERA6AA5tG/RucpCuzVQkv838VkUmeJkjCbTNn8G+Bru1ju+tog+1uwDPZ+yK85wteI8twYVcflwQBne7Dh7OP9LK1TOyaezHajoGuzHjmteX4HJjxDK9CarD9S5cHGOzOn60kIVecEypV0jaAuOTC3aUyjN/0v6fIxj3h2omjdaqvxsUhGwDFhRwOHPvvFHrxDIIXenlncoUnkhTOfAhKzT0faP3NhtAKrWzpyCrgr5FZ/CGkJHXldEdOatN/aZuuO+xRHV2Je2rp+MIyjvRer7kqmh8RObU3BlMa+JvMmdckhof2X2zYMs8oW2W7NuqFTmZkkjJ7gNFDJLZ0bLMNpqPyNm9d05ixJSrKxaXQy1NhM0SwNPj6N5CgLymrhqqbtdk/dClDmjaQF+RiESD2v1MaV15zwrBb55Iz9q6XVYq48f+bb2v7g1szdv5P6Q5shdQAejqsjtPJIZQDWjAzrObTqBR3Vwr5sG6RfRem/f54vUzSi+euKxN8SNciL1ay4kBjk5+orFz/RqKtnHh4RGGv2kSfejZKOCTxDmmOSEQGcenpD7+RgSGHzQSBmU2kTEDrs4ohFD0iL9UVbSAn1pPnzCPFmIWfxY7MpYFlw0AM7b8rGDzZ7oZOjgWLFgpakxIyuXYIvxpZGl1TPYzrCYpZ7sOYZ7zLa/3JkjkKIGZzI/Id0M8TeCt+cDPzuvStO2nkQCRBWUUWPu9bWX0c0=
  template:
    metadata:
      creationTimestamp: null
      name: github-imprunetapp
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-imprunetapp
  url: ssh://git@github.com/garugaru/imprunetapp.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: imprunetapp
  validation: client
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      name: imprunetapp
---
