---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-imprunetapp
  namespace: flux-system
spec:
  encryptedData:
    identity: AgB76kTw0rJA5aWtmQVcgti6gjbVmJe7wlnllsJcKw417qBo5o11Rs8rY46djy2bAPQEcDpCqEVG409BShShMOEwQzZCml/RmU60reog8zNRxJUKnxdEfyU/S0nm2BXsPENGxAhjmqFrmjh/cSQnexUyftoG9MzqPBbYfX+CUh9IJfzSBUvvFw/nNAmfialk2trj5hL9Dm0r8rVjpups/CMVYBtBRucRwzFW/iAh/P2IlaoRE/ghfOXsv6c02X7sdx4FprsmgS/9wXiVRUi2VNCqF7Lsga9nGcfd5yGqBxiy3zc13nhcmShH6avCMD6Cu62B2zKfhpq/2Dh8kKY8FYqtgRKAqAhdbE1a7Vp2oXZwBf+zVFQLFnDxJXeaRqiznDsgvf39O6mkpJ7SVCUSXdOi9fw5rNeH3c8Lqkh03w+fGJSN74JGM0qkYz+GGQ5EJH6k8DI1iIXx2CDjYIwUlaYh/KrxtYy8d1eLlJLuo+CKeuU2nflDks/PDIW4/4J1wNlTXaJ/0ycR/hMZJGkYAOv3C4dKg/NQzvreBrLA7T1MbQtKHc25GgwPZeT1Kgd0/yh6nHMzJz1bgktvN0IMGZqoeSi0n1XmRwt2u16q/ylbcBKAIjIMrG7kqUWG1XyCZXzCldrBiq7OgwDK0v0ouBTSAet04CiAU1ZxjXd6JgzIMQylm3+h4UQdKMD4KxbipIwTWDr0ibEqYeHb5XjVHB+blakT6on9bIiCZ7JzFC3Na1L7R1GVMuykggYW8cpw2nxgxuj+GVdgLNTj9Io57bcJVCH9esFn/XaFIyL6gyuXvYKLe2FzMz6ra8EtYlM8M8LKMB0vbe0sUgwl+aR9xUyRSEUX8U05qYqIvyh2JR8Pd3GZ5AWQM9wDsSfbG8mGdIiOz9cOxyeSRuNtRa87+t8hS9xe1zj/sDaGXp9OEKJGL0DKfGhlolcw1tmKaWOUAQ8vUfXs4x+3G2u7tVT4lOFx8/wKhMSVpO3lB9Ue6vtck+pJ8Q==
    known_hosts: AgB/elYYi0y/9Q+ZjW8Lwyrwuav2m3gRcSDE8DPLrK/H+sxo/oJQtaOrt9eu8Wz51x5++ttCjl1/vzIoMdiIePeAYIssNwtObJluIlsRAIvyQ/VCl0HZdOvRUXF93MBt1V2TdNK+wr5/3C8VG2KRSgG+jT0D1WTUV3ddJjuVFUvnn4dhFe+Y0r1gBLsJPOXK1ltIlhIdmsn1PYvQyG5GIINYB+sDnLUwyppz5rw4Giic/4Cgg0NNAoDOCMHQ2RNdFVluFZIHUyki3zbzyiEcQo6BDAzi4rXUaowVZaWR9+BSiubsIDvuJxN8cGGStFdxsMu6IuQMMZ5lthh08J7rsZCwdpx2MLwmI7FFkI0jd/v9Lw/GwEM9OqKUJPz9Lv+NDk6tTPtrTktudrlk8VI7e466Srix1W/zeEx6fKL/eTnbLIlQslVynrUdSoeRW2foVL0UxZrsTHg2p7IUaoWsCCQhnPu9nvGE8sI7CDtZxvuO6hZ2GOnuzyiitj382La1HP3SbPX+/xEji+UQ9xd1xjAKxDwrlu0s/UY9m4pdV3KxEgvKRvYkhJ+NODpVEhCydsODRyORVjiidE3GW5F2UYiS+wjSIgqh92IcoJQNe4GQIvcYkJTpmuwfCyyF1YXmPzlTFt1bVqXWcN0N7xIl/l7L5lQhGDHVfcgDQ1gzzz3NNqYyfb99gEbZ/Fqz7XukC9m4g/Jw0N6d752FEO08y5giucOfUrx1dbgYwT3KzW+xm8i/V7FaMsmXfW6yUGENv6iP8nvA9PlRGYwtvxOJPZdiAPo8eQCllfW4osh9Oh+o+OIdnvgyO1O8MCjCQiEpSNYP4lp0WuTUT39JgwSkd7r7JSxX6dtpTbUloKGLR/B5H/Ta9dkrIpMlXj3CvCe/g/h+uRB5aITpdqCiNAiESsXUfNDYXJyIwrR6ilc=
  template:
    metadata:
      creationTimestamp: null
      name: github-imprunetapp
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-imprunetapp
  url: ssh://git@github.com/garugaru/imprunetapp.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: imprunetapp
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      name: imprunetapp
---
