---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-imprunetapp
  namespace: flux-system
spec:
  encryptedData:
    identity: AgCaqoKfEMa+AY2IuGcxE9Efjai7rAh3DDh/Nd7mut2id8TCxfdJ93aet4HqHad/gjC5UQ33ZwCSK+Cp3lZR1TGTQbHAnY+NPDZwoxKOzMQqFjGUCTDqJaJahKhTAo7jNmLOWyfXtyED3+zdYRG3lKm7MabrK23zud47AuvvZB2bTAARo4kLkMuxBJWUUyx2pqa/PwMcyOlBFg5JyyczoZTtGBkSn+KSvqvVq5tG59gJgdmDw7+EgTYNSKRxhzHhNUxQULCHy7UKG9JnT9nmnDcBn2HWeeZyL+8Y8iLqpbwMp4l5AKY7gsihubC8csbRcHMyuPlduGmp72p+1NR8OlKvcF1pX49RRp/qm24LW0uEpknLwgCh4RYc5C+PmGI47exmhFTEQBdsznwUyq3irlcodknPyQy3KBt74h1QjGungIc4epl/+0ASBB1s/CF8IXOFEbIkqt5zUJrRnZxIOZaxU3kMzxr2MTDwXHoajJmDyDhibM4pJZHo8iaL/FgPjmXTZYXzehXeA3DUqHfG50n82auli318tI61KjAwzUKqRK0/APJwc/JfmK+vT/NmDr2LsuC/6TBMi4nvwJCBTC5on1FAcHNUoOhgETwBXHCe6yd1rpLulV2IPbJ94zcbSZhLfr3MrkCG1GhMBxMIYvSkbNo3runGblDsNM4nz5kd6ZJFLH0NBtUx9kbTQ0WD7Xt4hSZyZfzpZzC7sOGV7naiPndp4/B2yOghqWyccb1pb0YjPziW4kwl5Ir5ntlJLNlpVxk1kXmBE737tQpD+SBKSj2Z4RjbL0exKUohypwif/3AXxgGDNuLFy4qMbsXmk4zA1nysWVPNhTq7sf4bnDjmfmdjWzNU4pCrIqpdDTONGIVR3AQUvHoQf8NH2m0P3ukNTB/PGGdn9I/GgEQq5F70cV7BJ/5Y8pZWfIL121IGPIbC+D/Yj6S6VDaGO5JsTbQuIC8GHP3eJ9EXCaO9LH0vLubItTwl7NE0z6FrL/xa3JZrA==
    known_hosts: AgCA2y+asQaA5q0E/qQmDdY0Zv4BtAcWSWq1BIsgCc9d7Iillz6JDQxKPUvt3umYnFFN2rf4DyNv6Qm8san+cpHtyVCVA7dpCSNkN71mekHHu0RsV5PeCFvVSHFk3NRqnGyKfCdnoPUzkNq1dwbyeRBnUJw539/oYpt1sc6YdxLvzlxputZd2LBKR5ulJe8DOql1Kq6LXdX0NPdgXUUnD4oumJ0mY1Okn1eC4gmzcQ+yMZg1VqgmBq1d4CQ7PI3suB5sNJrYPYu1AyUQ5MSk7DNc7wp/Vf2uD2Wx5CTYywjR5JmSYY003tX2w0t35mNpWStBHexuHiOgwBuw5A3OwMJGuDmP0uo3tJdcffqhrDqcHZoA4crrC24p1DrAZdb0LKjAyeEbSz9M/xJOM/co59CqIfHG3aIlmf557JquMJ+F49ITiudg6Le+30XIf2hlhXaeIeYKYPApKvyKIMvWcvE1q7SUn88XRKad2qlIPlelz+B1VJ4kh25P/ash3526HLKCeJBziaLtMYgaj76IeemoGEgzpR29i0pseLEEnCICfbX3BalEQYJ8Y3+e86GUDWNVzJxMCZ4HTinuoowJQYfCpuqXtsQ3RpVXi8BAxU8rc2Hn5WtGNBbGvdlhxS9XOBKsQoPBe3jVUhc4pX0j0GL/2SGALtdesjg/Vcr/6yLMhP5H6il5rvirRtP9kDGGH+gSv4wc5ML2zbCtp2PkiKXfLmBOofshf1WvzaWCd6bz7oJ1tWM9DNzQgYoZsqAo/yqF8NTgkMMSx+Nx+F6RaB6tvv53IVBfZ977aDSe4bRLBlE6ahqJIihFDvaeXcKD/Bnt7RXEJ5MBa7LYsUIGTmHrTZCm5F9CtXvsd/uKe1wtmXzS00R/3cKLAenIYrAwuDtq4RaZQ2r7jrzf/WhZ5SMKgd4aDc4T8DL2WjQ=
  template:
    metadata:
      creationTimestamp: null
      name: github-imprunetapp
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-imprunetapp
  url: ssh://git@github.com/garugaru/imprunetapp.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: imprunetapp
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      name: imprunetapp
---
