---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  encryptedData:
    identity: AgAlY5SKtwIa3CQ4Xxb7YHPypNeaaEk5r5/uLd+8cyWbpSLn3mDeOFnj3cfJaCPVyRT/MNKTuEZ1Fqo4V4Wk6WP4B/15W9zse8oOW1T0Qk5cVmZMWiYE6x0LXauYguzfBgWn4y4VP96vFDkx2LhV5yEyvnlYquKxO/+7fEwnIlqqYO/tHB9e7yXIC3Bh16d5iTYpV86R0aLK/xqjSVR7tD/xCu97ddmV8EuaUkyYVbjprmxN/aCv9F+j9Sb+p0O2kSWDwthdpSEbDUiCI0ciwZC8c1BGM5Tg0vxKfOQsPr+Z8ktV1v+ZmphsJY2l5R6R2bC1/nHM6s7psUO+HqhUKtek0mH/Cb2WlPpTm49gUy2ZH+I6WHvlm+OqZRg6+Np9oESB1KfVW0GleaBv6TruYgpuYK1SFnmndA3hs+rhEscKBg2/bko4yMNEt0Q+RDsvUNGV2Lcoom78LScRCUaYJDL4RxtZDBzg3u4pnA/bq34f8ulI5dx3p3p5PtFnHtK7eZpEKrymkxZyGXEWQLc5g2E+0PkfudnnwoekE6o+SxFBAvQ5CxkFuY+XwvcO7Vg7Klga8N2U7bXflghSS8x0p254xDK5IE9oxwSYN/Ock6mJOrVTtjNUAnbra1x9hUZ5TTt+FkjYA9UZe+ORNFeJb0Mbd1lIXv8RegHvA+lVS7pu5IzJEAEtBIflvlDMmen9K4YqOjNo4adJSgVbBNKIgOCDvrZJU/qUTVpXEGPS68BRnkVQsGLZ59wNyaDMrIh/4NmBtT/wYQyN7WGthhsXMpYqXclqDxz96+RIc79lR5ayRMozj7iybZefG52Ty3cIODK/+coVtZ31mkgakp41peR3xyUjy8gEBdfs5s5yNm+nd4BFDgIKKbsZ0Y7H41nfnlO5LzCsGIr7ow5wi72q2TZgz6rpYPAopfZ0WDCOWsDLW8PIQb8cQL7JBOPUJmDiahyw6d/FsoXwa2ChnvfnX1wu5ZLOwgI6Ct3sGABrij2sPFLBFQ==
    known_hosts: AgAUn+u7y/Fv07QnG+/E85QHtzxZLgVd0w0L7R9y4HtyaTrqZ6Wvog+kSgb/cAUFbEK2oEsxxNfFasNh9NCwUXeRqltmPgIYYQXmKLXgW292yVFavsVWfz2w64pzRXK61GiSgiu9WiH4q9KcbV0lQcerqeoIrBvQ34b4XhR56gaV+H/gAIVnJAaTGhF0bKrzy+wAb3mv42ramapWsCZksnnby+7T3JlK6Pbqe+GW3yxLz6gx9QyzdluSov9d4NDY+OlFYcjftqvOUUpGw27LKcUK0zsswj00Tty+0VWF5wKmKFt2xCnSp5c4ZlSyYDnm2VmiZLGiNzXT9eLtiE8qO58Sp859uzr0NBzKmUPObE7JXAXirCsCMaRBaV2IPaE5HBrPR+U1NT8xNvCYSc6yLf5XuqGjTam3PsFnQV4FRursnBlqWC9S0DNhxW15rdY1bfMXWjubmV+lD8XCnMAlJYp7hLttEmV8yT4faGLuCt3LbQ7ccmzzdDiHo79Lt/kgAOFtvFVLcb6XGlxNsyLJVrEKPvo3Rm4cbknqLjjxN+I7tlgSZCb+RCPGuRWn3pgO2JURVsVv+wvIJ/IOxlM1VRmZRb+R1WYjBLZiehM0c8BXloNa4R0tOuhH2ip+PEXiiChVpaPTGbfG0emQgygmgQX5+lUq+PTDQECgz8OXZN1rQkNj+D1YFTjQjEDjXrPCL7f4hwVg00Uu9Uvb3V6azVYjdFWQlJCZkMS9VCtGrrHpDN0ZGigoHExwLYyEei59yfsT6wsZwW3evljM7AG3mCEIRX9e+BUxf9Bb8ElNS0HN+tmyLJbk5zpbxGSghh+RMs56RM3emDnLX+Q2AcSvuvyCrHR756ynjm+duTssPCUDUv0i22pKWOmUMwDKrhPueQ0aQTx7ehvJLQ8Yw9oNi22SJtXOilfZeCfeecc=
  template:
    metadata:
      name: github-imprunetapp
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-imprunetapp
  url: ssh://git@github.com/garugaru/imprunetapp.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: imprunetapp
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: imprunetapp
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-imprunetapp
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: imprunetapp
---
