---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-inkture
  namespace: flux-system
spec:
  encryptedData:
    identity: AgBpAWJgfYQ712pG8PIUZwWMs2jScYmcUHUTFYSxFevTS2cC1tbkOQvabAA9yAW7DgVuC4ihWNQlJLur+lk//gq2C30xXt2YeIp2WdH2SiILlKbiF5KMW/7SfUv1i3+YUEzeNISMF3ZT81CHeDNvUu9fNZ7VGJuGO1rl2jyPAODFy53rFanZ8M0cZOxUG27jg/vXzGKylinS+Cm0Akre+Dd4nHhBMvX34J5lkiRp3NFxLe5b0ULeHqdbIj79E9c3YnTDuV+AlQ5Toyt0lIXdGobuJjcaaMX0DquoYIlFb6lqNzKCkJdpoedvgTOwF7+Ik40ZoULN1et7c0+h7t3UL7ORnJZdQSm2S/aSIoup3IYrCAQN6ub5YmfeC9ix3IrlrptMG7K5l2jK6JOL/V6zYfa6gs9uVfKexWSg3IpRDtNpVEIQshiKKiix+aM2sEOCkoE6tNre3VYch1rCMR7CM2oj3Ar0c9rY7sNlcw0tZLjatpbrrLvEVfrlCTXwFTMqZ/znTYDoiKZrAwAklsSMKZfzEk/NNHi4tEePZALGxRUSIMA2pURngE25jkd2l/3Lc/10sPdmvutRvMBLcznitfTYFmh1pwteywGnfr8xTtUzitl1e+aTgQHOzHh6SwNZfuItQHVvf0wSN2iIktnrIwLe75kDhRvh4uy3PzgyazCfOo3jrgWCe7hjK3ZsSXmlRZtHPdg9r7VmcEkXwBRiWUzRH8vrt1zINqnAmL4Iq+pUO2GFHcIGNzaKFCn8wphOkompgzRKTfXeI8enFUS9XfxZKKodiJdHr4SgNHOL9QPOs0KSvYST71NtWZFsp4GKBFrpavwkq3QKDmmqGBQ7kskgcE69seyV6U7BUT2j2XlihhTxu/dlWIE9gKesEq9o/y0DSwP4L0XW4XvBKEKuST3Oo1bgha0EWS6Jf3ef9sW93VkPZNOK9704IDDqDx7ctvfjT07esIWUVHdS6mCXtB0MjPjlJ2J2Yz7Fc/yXb1ViRqea/g==
    known_hosts: AgCPnGuZMa2+yD+XldvmUUleSMEvAgnJ52tHlRmsxvMTbYi4w5eXq9hh0jY4ewZIOBPmE72qWXDZjgFd8faXQ5MXHsRoA562pMxwlQTsi+V8IrpaEbi0wiADnoguaPTbtmD6f9kozybNfPpIu25AsJ7DwmAvjI5ct0PlI2QTVWzyKULHgpZRwpFjETSFkmtXJyb7/dvHuPmAxBw2ugiFU7fLF6TcwRfdj8xSbjfX9m79Ki2SFM3FWT/tD5LGOG45zoi10PEeCT7lxVY/pE7x45qnH/WBsX7VGeQHIzTnO33o6wEH1B1Vb74hFigzWY504dLerzFCWcTGrM5nB9maecrmg4tXJTts1/V8jOEFTpEllJlbeLboxD9WKL9JEKE9gijcqiz6PhaTBLfWHoNp3Os1oFN38P9whU0CY4ifYSyfZJ18l+RNhIa2ymOk41+WB4Mrk5QG6+rnRj7GTH7arHEbi7QHZmFea+fKQSou7sqTyF4HtdTRvzjfadlI5JclX2oXyZzcTWYBTkeuq2bstZl33dEViFJ82H99ELCAPEzXgu6iwXxrnty6n5Q/3w89e1DrxH+GkjiqJ5jzH/a4bkn/iR0hxf2fN2ZHbM3GHpKcVtNVftmAAaL5hLdleLes1ZyXmo54O7nsOV6p9xxPWhCqrTL6GC6tPJt72NPSntupblhRTVM1jfNHmoR+sWjiq7T9v7Mql3+WGytwWlLXGMHNjBKehHvTfhzWJ9cyo58ajU6I13YvS2stNQwodgpDdxCbz8nRZDLBwFoL8AcMz1j3asgM/1jLsveojqKwgrKc6r/ciQQbi/0SxuJlHFKKv+udSbIKqk2j8MWmcLEkEtXMVFi9jnegJd4+/D7K2tojkbGBYDvHC6LzgjFhPAAqwSlrNI7pUArwXo25cHJu9Byogb8/TO/vjCLEaw4=
  template:
    metadata:
      creationTimestamp: null
      name: github-inkture
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-inkture
  url: ssh://git@github.com/garugaru/inkture.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: inkture
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-inkture
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      name: inkture
---