---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-inkture
  namespace: flux-system
spec:
  encryptedData:
    identity: AgDYe7GIBowQimkEyck8LOy8FwuvjOZpEiIT6l9GLaRJ6mODdiw2cMZaaO7BOOqniw9kJF0ZQwXKFnjbrtmrTIF4aYIqJJSGTV99Wpfv+fOY+QgUfJqp6BGItMJTDTA0B7E6HdoF/Ck9MMEY/l1SgxxiS2x/t4EuRfBuYxguRIR7u/r0vz+PDz/beYJf4/UzAr7yMcAXrKDjF/9fXqfaOW6gZcL8zg3PIvs9FeMoQAqK2UJVQGYvu1cKpKWk54RdhwbFnTAlnWoa7ECfa5Gna7Pi4SKMVGWWbmM/pPboQc9IR9OR2PrOwXc1278dJSh1582LFwIzJrXbYxqY3x70wx6XwFnDAVLmkv/vBJ4CdF6062Ng4hvCDsrWVN7IcgKg/zg2/T2dD6/dG1PgkZB02MZqug7qsvTHqxb5TzFWKZUk8sGfWlGFB/c+IGvIzF8gqNVBVCf7c4bLKOYX0c+7HPPlWsIomGa4MCu0RP42vhfUfmKSw/CXwBWfUdgrSmawREoJ2SjLL56/wpPImcANLr3m/WGusGTf+e8y0W+TK5jeiKPxaSJcEMWwDx5itpFajP0O6ut3kec2nlBMuShcdusLbV2UubUMc5H3nHd6Ez/7ZMx8PyI0skbu8cJamstyZefSgMuJaEljMwRek9kEjR1qUPbQ/XYg/64C7jcB8RFm7l2Qc0nw/qKACNqNquIpL7V2AVXlZHKYQ2Z/IjCDaJPFNN5xKtO38Uq0IMh7mpFKmtfW4sHoN52gud5KYYbstEIlcg3saD8JOcbuSVPXgZKRQBklEdULu1eviHhMCXr8doVKqlXVWHUSTnjABuM+Azr7IImL9u/l0yPhMfMxJxk5ZM2getBWyAKRg1Yzq0JeGldqg5APl1YluIn46W39FFf22wg5u2qSHDEg24uyf5DDP2D+YnJmk9ZaAdtUswGbp37O76KUAOGBaeBaUlmScMmPH9udsvBJ0ejq2A6ibjVD6sUZxxZjrGccPRY7WfAknhZbhA==
    known_hosts: AgCD8Tujs2JJWeS0xLMGMZoFojSFF8FplV08uxsd+W5tiziB9UJ5KO1giqRrtGiApDiHlF7wbLZgfHdnX27rLx8y2a7vqoOPxQFhfUZ9iI6nGk+u2st1sDePXRyEw7s8PN3B+YDItb6NDa9EqF+QvE5umktCCjAghni91x5pT6fwCGadm8Q6ijRAjaBa7p1P7sJoL/5W9dP9ebpBQa7qNR3IX2zwYrjhIodjLUL2B4LxGhgnSPqk0FIGjZGBE3zzaI7TpDREGW1D3rNoI3yfx2wChY4Ke7CNV5GPTqj7MZQbOcIFraefnWqIXurjzUxtU2w0ylSmoWwwgQTxHbihotXN+AlY37FNt4sYIiYc41DTdqlA1SHdi/8BftCIlzYzdRD/LXO4tytDL0/4wwToIX0C/VUe+cZQYd/y1Bnm+KourzF8JPSkowEfQ+QAwos9cMcabLkEvhMDIcD9sa7z+2uRM+S/H19P3hpuqQ5RgYbBuo4vSqJiVwiLgmUXRdIpcbyK+UTtYUKqp8PBPsZosJCfkejs/hjLNN80XwjubRCP4kCnsfY0cE4y1GVaJE/YcFZwKyzmBY1S3GLZaLgbxMXUB2zBVi0+EoRm/62sg8tHsaLMyP7yRjL74Zd2fbo0VhRzvuXOgB3itA+69ipOP/kJV9JSuA6W2aSixgsG6bNtTxQ0UJ78fYFJa3PtM0TjGgNdpTgM7FYHmHjAcHD0mY3CKuvT3O2UrItgZosPOi0lBTy2FewhY8hfqlPE9HIjnfI3VEYeuqC5VQ1b3KGCKygru+G4v8mqLel+g2NE4owPC0b4n0ktwkVsci5Uh2u5VW4XLGngzF0QxGdD3hbfo7klnmNnO7RcAZJIdAxDafFvXva8EsC34dN48BiatXP+pnZUCudHo6c3RNM9gh4uLA/qHHYLncNA36+U3Q8=
  template:
    metadata:
      name: github-inkture
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-inkture
  url: ssh://git@github.com/garugaru/inkture.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: inkture
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-inkture
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: inkture
---