---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-inkture
  namespace: flux-system
spec:
  encryptedData:
    identity: AgCRn9CYS7RZy3bpUbNDA9id4rgumtZZ+Xhm3zN7A+lr6dvGK0KoL2MoHzDcBiVCp5AtCb5KwMoMXCmQK6lnFLPiSZXHzMSqsd2UFU0ZNO+GS4AhXOxplL6JnQEgdCA3FrDWT2Z4tJpkO2aU6xT7cDS1vmwNCxM24Pyd9LTGDEHG6OmTLxj27fksB/6HKfpJKKDgeUtS/Ix9xQHe4Bs6fco3NUpXxhydzajpRcRnfPgzChqOgMQ0ls9ey4fWwnFiJE4rp5JCf0uTWDKS4r9s6DxYAvX3bvwG/akOfKMipUNKVHM6dwKD0Q7uBFNnPis8MXiLM97ht+Z8soKg+FTdv7YUvcO8jtkHuFxNnUtclAeUzuK7iKhvoNW5gb3jEhtTTJSpBLI2sxyFxq+zOjjxQfSBXP18064AdDXWBfLDyxL1NiU+Mg/ywcMNVbwSUxnMmTXWdFqxZEJaFpCotHbGPLy8hT/hMk1oRvuVyWTzl7WoExU4QlL5qrQdCpki3zNPRRwGzzS+jHbSki3NFdK+tEhqacxGdMSFxC8Iuk1NONdM1fGZEElRkqBd8vzrNWCuY409CP6OiPUTy5kA/zRu6fcKnFSdcWqpLT6i79+4orNSo4D9XjaP7f9wUE4n5HRdYZCukn7kYiuYKGsxRpI+8irx9XOctOgiRmCQ7zfDkyRmdmdURjQzHRtI9nx8P/dvmG0NfsyT/t+gsxhat4cqekVnCd++MT2Fh8CGfL8j0Q0d0e1OtJ4gTenzwpsXbu0ahpc0CElwiPmbq58PwATXknaC0ku80jMUVncAr2vJk4enehVu/qGuYMsPHxctQ2QQCOV+mf48qMRLJixnDxY1Q6vSs071LeMD/0ftW31URgOzZzcAWp1mbrgp2AgOvqarXLDtyeVsqVEsSx/g0biQpKEL2R1lV+PmwpReit5kTsPxmpj9Tvf3LQLJ/BpV9cU9GraMOWtyM2D2iKKZpPB7MVqnSq0QMjX5S4gdEGV/rrMUYWhPRA==
    known_hosts: AgBN8LgUU0Iscvp/Pnt8CWttw2dBe9SBOKXXYtl+WwJqss276tQ8J2PwWJcDAi8J9BCJH1qXvL6lGTiTYJtx2gPRzFyVmKkfIpLPdsh9RcPNhKJ/I/4qNJpzJiUz4o/RR+N0qJQCmptfqdWm3UJe+cW/oZCwRX2CYVNHAdpISkyMKVOgR4AjJPtxvfZIoJggiQ3wCwSR3g0rE8hP6TjfCdEA/zh9R/zHRZOowDHcA7Z4zEIQorGV+wb5IdJ8MPrfuMInRXya/j/SH8Csj73ym7OGSn0GLZSttzeR4HlrSaJ6lOeChv1cYExBqekxnYzSDmBMKBFIZh98grd3Smy3s+g3kaZgWwQpYuk0BK78CQTmaxk3aTjxvj+QONLN7E7vAytRAlKuGIAswb0k2TOLtcsTYTu4N7guTQT9yYcgdtpHMaZzTSIjV9kvcd9yQJmUEnoF4XWQo2823Gd9lXuoYm3sjANFjq4u//mCO/LEaIS+Lbzn/Kve+xMQ6mOqF2zGDezEqVaYg2xeFtXt4W2sF4Jl2OhmYSLWCUxo8aIyJhF5kIjOVh4YY8tLdlGFBSxW6ZjmlPaXE7dHM1wsTuohuzmW64/QJGidg9j3JpmLp22NzQKPC0+DtG1sV4cE70cHzXGd2mNcg/2wvsNeJkH7XivzkI3cgsvndlYgTrpsjJsRBQqA/4ZbCViBlCbf4yTwyCqnSBDW/cnraSKmIlxdmvVelEZDq1TW4JFOqVwX64YoOnxIaOpw/aBzfy4cwjJvR94M467TYR9tuv9Xnr5TwOeWsKL5SSvvVASKchsQ2EqsIzaI2O0JPH/vf2qC/e88yHC0OoHdbOkBYmzmRkfNpJw52E4yRDQSU4pipp//J+4cQMWqclfXQ65mg5gbICBRd0bAZ4j3fkFJw3ODGMUadnOaG35nOf734Xegmts=
  template:
    metadata:
      creationTimestamp: null
      name: github-inkture
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-inkture
  url: ssh://git@github.com/garugaru/inkture.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: inkture
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Receiver
metadata:
  name: github-inkture
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta1
      kind: GitRepository
      name: inkture
---