---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-inkture
  namespace: flux-system
spec:
  encryptedData:
    identity: AgBnNmzKq2d12NbuC5AHIzx1R7FGgU/cEUSUWAqPxQFIdRVr2V6qmLr04orm26cWnP4dWYZ9X4eqI2ih8TL8+dg6AaNItbsMp8npV3EU5mWhDz7IeFKUIuPdycjoFvgw8sNDCVTE3veZor8j4Jm7z5YmGSfz4LXQFa4LAzdtkcc7SIaddDEmUmcNEk6A1geSUqmpbl01QgcHMv0pZYRcP/cZjdbfEeU7KtoUo3tjYjuWaKWKJdTdNqsH6KJv1w6uErZ/p/qGAo7SkJfIB9bgwB4XFyHVBtFa+Ofv9rw2bZNsokG6Tf1jvifRS645Fn7uWruHCnPlX9tibdMLwuO3ZJ9Gw38JrSw72D3G79gmX1N7AJRF/bp7/XdAfSViS6mb/j2+0Jf0UgwEr59PbdnywQY7Xga8vMEup6jfGx5vP9TCtDLARioffKy/7A/eeZFaBEp9DgowIZYXttBUWRvkP/4nrWJwa1+kQ/zVKfzU4qXzrms6ZuFxL37Of1Oj550hGv6PLiQ47q/sH0yfd5AuKzyKKTbeanu91hYYIXlSVUoIYO9n30jdI9Eko6Lu1JoSufgIiXSpd9g0LgWjY01FPghiafesxmNp+ybl3SRvxoYCnfIQ4hw4OKaz05xSln3kiCyZ/+LDDjgX8G9TB4W+SDTLl0ucOJGprQLjwlSoo8i0bjgrCQYucDrJtdTlxQo0UeIEG6NkbQMhl8VEzj2GGP2uo2osurKcdn1xKKhDumed7CyhbZXhlQoh6uXIQ08T/bZ1t606d2sXBJdZ+Ki0UqDnid0b0Zy2tVc0qQzTItwXH7uip6+VNm6Gqa2FifCARIaMt75JbvVSna6M1Wj6ev4b/Q6o/fwaA8blJfjywHMoYhoXc781JvUrZi8b5PdykfMarkcSDECVViKf5nHVdeqEts+dgQwtyS282eRCtX95YVhqjuqmW1KDn5segeM+JLUwcthcitdfCQuQzk33SWSdO2XM8WZUYmgnjhpYb8bGHeaEtw==
    known_hosts: AgB5QI7AIrQU9QVgVEcWLa+WCOLIWCd3Lu0z9xvlUBJz84+NOKRBbF3+yZPkQJeAjO9ymN7V05Ge4Hsr3dwYbDzruB/77AidigzPDwHlrb9B3OrMia2nlRV9Zm2gw2bUxj71FqYROaLlm0giKPVXZnihwifcJtH83z9kitsRkQiyU2tgQfLjmv5NHjce9kp9HWPyq0cfcLS7rd/OGS4ZIPbr01Sp+TGc/6uL6OBWI5J8gWacgR3B7hLtH21lS/zv2ibW6jPWTRxllotbKrT5sbDTeJffye4nsYMqnWT4XkDW5cPCaXa2npdzpzGdcT1kOMsSc47qoknolJ9gETJZBq+sJuupokRe+Vy0amV0LcXvpcw/to2MWfooC03KE9NNuoapuA10nRIeNWR+n6YGq+FAUcZemDMX1AHNFgtN2paIanzhaMRf3RkfWC0vV88HmcgFN4h5aAzj/ECD2igag4UdG6vSyBCZZ13rV8qlJE3bAuUxbsT6eH4ViH3/k2K1yJkcfUYgNmpiIG2HaTN3+dqWvnIDHFCWhUptvcmtNzhqTChQ2HX/bgGDUHHavJnnyXLcAjg5K2yaUHg4K4V6E1eLRxyKzgEefSOEphMBHpsHQmrackLRG0ZzMxfGsWx+72NsOy7jsxxKrsNT740oBaS/ELF94kT4VZ4+fOkDp4kB6cLmX/bZjcRYEHbXgLUbtrn1l3Qo3TS50MxqqlzSUwBTbsJcdEF+HFP8MVO3G0eB+mZpwNu0D/iOC5LGDCyYV04eDp51EmPIu3+BhFF7Rr1MsHLOUErDhx3XKNp90ItoH72f8o+cJsTtOdvU/ARICyGtIc7aJEqAEjL6cWPbeOi3yVKhRBcT6zLE9XYJuvLqLsIxBWkw0bRe1yS2NLgWziKlY8tnQtxbqxKrKRcQh09O63IfGB7B3YP3yIs=
  template:
    metadata:
      name: github-inkture
      namespace: flux-system
    type: Opaque
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: master
  secretRef:
    name: github-inkture
  url: ssh://git@github.com/garugaru/inkture.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: inkture
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./kubernetes
  prune: true
  sourceRef:
    kind: GitRepository
    name: inkture
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: github-inkture
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: inkture
---