---
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: jaeger-operator
spec:
  agent:
    strategy: DaemonSet
  storage:
    type: badger
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/auth-url: "https://oauth.garu.io/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://oauth.garu.io/oauth2/start?rd=/redirect/$http_host$escaped_request_uri"
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/ingress.class: nginx
    hosts:
      - jaeger.garu.io
    tls:
      - hosts:
          - jaeger.garu.io
        secretName: jaeger-tls
---
