---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-music-pv
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /nas/music
    server: 192.168.1.5
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-music-pvc
  namespace: music
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  volumeName: nfs-music-pv
---
