apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-config
  namespace: adguard
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.1.5:3260
    iqn: iqn.2026-01.local.nas:k8s-adguard-config
    lun: 0
    fsType: ext4
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-data
  namespace: adguard
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    targetPortal: 192.168.1.5:3260
    iqn: iqn.2026-01.local.nas:k8s-adguard-data
    lun: 0
    fsType: ext4
    readOnly: false
---
