apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minio/credentials.yml
  - ../base
  - ./cert-manager/
  - ./oauth2-proxy/
  - ./links/
  - ./hass/
patchesStrategicMerge:
  - patch.metal-lb.yml
  - patch.ingress-nginx.yml
  - patch.prometheus.yml
  - patch.storage.yml
  - patch.minio.yml