apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-system
  - ../../base/cert-manager
  - ../../base/metal-lb
  - ../../base/ingress-nginx
  - ../../base/storage/local-path-provisioner
  - ../../base/storage/longhorn
  - cert-manager/
  - oauth2-proxy/
  - ../../base/monitoring/prometheus
  - ../../base/flux-system
patchesStrategicMerge:
  - patch.metal-lb.yml
  - patch.ingress-nginx.yml
  - patch.metrics-server.yml
  - patch.prometheus.yml
