apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/cert-manager
  - cert-manager/
  - ../../base/metal-lb
  - ../../base/ingress-nginx
  - ../../base/kube-system
  # WIP - ../../base/monitoring/prometheus
patchesStrategicMerge:
  - patch.metal-lb.yml
  - patch.ingress-nginx.yml
  - patch.metrics-server.yml
  - observability/prometheus/patch.prometheus.yml
