apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  values:
    mode: standalone
    replicas: 1
    existingSecret: "minio-credentials" # minio/credentials.yml
    persistence:
      enabled: true
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 200Gi
    environment:
      MINIO_SERVER_URL=https://s3.garu.io
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://oauth.garu.io/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://oauth.garu.io/oauth2/start?rd=/redirect/$http_host$escaped_request_uri"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - s3.garu.io
      tls:
        - secretName: s3-tls
          hosts:
            - s3.garu.io

    consoleIngress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/auth-url: "https://oauth.garu.io/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://oauth.garu.io/oauth2/start?rd=/redirect/$http_host$escaped_request_uri"
        cert-manager.io/cluster-issuer: letsencrypt-prod
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - minio.garu.io
      tls:
        - secretName: minio-tls
          hosts:
            - minio.garu.io

    ## Node labels for pod assignment
    ## Ref: https://kubernetes.io/docs/user-guide/node-selection/
    ##
    nodeSelector:
      kubernetes.io/hostname: "rpi-04-01"

    resources:
      requests:
        memory: 1Gi

    users: [ ]
    buckets: []

    metrics:
      serviceMonitor:
        enabled: true
