apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  values:

    alertmanager:
      enabled: false
    grafana:
      enabled: true
      persistence:
        enabled: true
        storageClassName: local-path
        accessModes:
          - ReadWriteOnce
        size: 3Gi

      plugins:
        - grafana-worldmap-panel
        - grafana-piechart-panel
        - grafana-polystat-panel
        - vonage-status-panel

      ingress:
        enabled: true
        annotations:
          # oauth2
          nginx.ingress.kubernetes.io/auth-url: "https://oauth.garu.io/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth.garu.io/oauth2/start?rd=/redirect/$http_host$escaped_request_uri"
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - grafana.garu.io

        tls:
          - secretName: grafana-general-tls
            hosts:
              - grafana.garu.io

    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        externalUrl: ""
        nodeSelector:
          "garu.io/storage-type": "ssd"

        retention: 2d
        retentionSize: 5GiB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
