---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://the-data-appeal-company.github.io/helm-charts/
      chart: oauth2-proxy
      version: 4.3.18
      sourceRef:
        kind: HelmRepository
        name: datappeal
        namespace: oauth2-proxy
      interval: 10m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
