---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lumen-credentials
  namespace: lumen
spec:
  encryptedData:
    password: AgCpy8wJMDwvy1uAQiiOqhTX4kLdCNYfm+YfmPjku6dq4NEKdOmC0PA3aJE9jd9Zyqf7YN8r/bx7lFaQlryIzw6i1UZGUfBrNyxI72li7+kEdR561/pSad3lhErrCJqj8CbN0oLaWrqNHj1sOadZ9s+P3xL+lib/AV6Ovk28ICE6xojIRDSnoQpAMzrSFt9hjkv/7QfuSE1+vVXaJAH35DEwtRPSjWoasMOdySkyZ2xlMH/sDeF8FW7/Z0I/HYUrFGal4W6fv9Dbb3wX3d+7VUl3gaaD96JD4MYm5bFH6h+3LMNmkIeUJdoG1sWldyJ1gXR22MLWbrbIzJHSfPurAtSF763d+dPWddYLy9juwLrM2C4YQH+WeiElFEhTLO8nr3QaiTfSCJ9dO2p5cz3szLevz3f33Xle4F6Z3G4QG5vJwIZACp5CA9+SD5ICdu3YBZz7WMzuzE1gh80xiR075P8PRui/90//rbcc44Tn/MeVFWv7k92ZV48q1JC/M9bAsEbnrCkBnz5NMRVpUGDMwiX0f/2k7fujaa+IgEH3CyEFy975/xnTkxJvrLNSudmLBcy2K4x3x/k5+6PJt9P4FSFR3I6Ez17RWPK6NnbA7nzzCQxzlrepMX7JEC0g0t1Wq2i4In3dPwaw+sTYFBnara8CPRKf/58VF5s85jIRPx0fwIpeZAAuZR4Xu9UvX7kxLhtzn9iCntIXd61LyDGUmLK18HxzvoA=
    username: AgA7p92b7X5JNLvKC0OwNunjDqpspMCwP2cTYGBMpBgxAgRyHDegJc1dqdC0nvp04/hwV27ppmK4981+KCFokQ7NN9fY+YlMRs4YdEOHPek7dC876dOFmAKSwYc/Pe9vOymWXqwpnup2hg7xpG/q2jPGiV+mB+VJFDeTU81mTnGlOOL0bAbHAIvbYGt7e3haYE7gWn53hH9NrEJ5fhO3nRmSAAZMlHXXQ6Sfpu3Xk88YPOhygog12X/9iE30aS2QTke0j0Wt7BhXHZ0ZfevO9JeSZ+lE5Y4RmVJEVZ9c9Pqv4eZFGvOjncxpSx/DTAHBaN86+Y7Ivwu0ymNU+lEBp73LYqubPvn+K03VEAi2Pvuhgy9eGpxdn2W9g01cdJHsX/ozhkdNBAP+sJp0QqfZ83HN4sm1eDzgJ5ypkYwKi0J80s5i4acubcNveNd4gb97afYjkepQvIbBaysniJm8RoJwxRHlHbHNJJYJV+qL+LYMuzFgpzD0AchPYqFfvjBZIKpCSKClvjHc/Q3vYv5zWm7mWGP+JDE3GJb3AzLDsgl2peKljiBczpQf0NkMxFmMbh5HJuOCfVYaFNlJeK7vz/naWIwYisDdGlJwJjmLc9t2cEWePLfePpMk0Lz3RyqjqEfFfxnHlw4wn5OoTuK4tIZxGIC7osJd5Rr23QI1SkfBIuf5OMQbXG7oMP2+bkUKRw/jWLYcuxFatA==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: lumen-credentials
      namespace: lumen
    type: kubernetes.io/basic-auth
---