---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lumen-credentials
  namespace: lumen
spec:
  encryptedData:
    password: AgCKoPmFya97PN1zT1BoBsI9h9AnszNjqreKlDapEelW7NUS1G40iBXRsF6+9EyfKbVWC7iqPeFSYVD1d6J1fhD3duRUqPi4P1bP26sjQAENhNcqVQ3/zRkvNfWQ4Jntm7Zb4cgRL74cooc7q32Ku+r7EFg3/U+PJ++2MVucJ0lmzxF+/R7fsRlpy0apxz0khYsFM9ShFNOST/9P1i6ncT+YD1H9BQ6DnIPvrZATnpCLpGfwk/K+bVyDwWDjsIFaWvVjmkTqyVLon//HcJ5nAYMIWkseGcb3P9dGnKwyx53GABDkN4XWF42PCx9LiLHOitUt70bqfFDGYbKS8PQbC+x/D8Onyhb2bMbVlOmKRLpNYaPHGrBBHBfv3EKiKjkC5wCSdkyuh3xe4QMw4T7Q5/AFYRyfoe6xY2znLA5Dkd0leALyl6UaBKARgsWqr70WReuuXIa/hs+ZzkseM+QXC+P+B9mAljhscSwI3Sv9JqIRoBIVLs0RuI3WkwpiK123FfCDoIq0blxV0L/994pBWGyVYTzw1d/t9SdKo43utB4aRTwCPe37r0ORVYeRFt3b5chmlJfcZZEltP25lCCV2LRAlXULoKgjsjNzqiEVk3fy6+mMOTz+jmrj5OeNabF7gp8TBWrN+CltRGuaKz33nf33AZz9yZTq6LUFkSbj9ui8QFPkkvRPOEjj63ocDasTazWm7vyxXXQ/Q5XM0da38cmOxVk4FE0=
    username: AgA2ZsbgBPRazs25C23JzEPAuA8/vgKOD2nXMIijyu9V9lUpXABsQ3MTAp+L5/7w0MKC+N00Izb50FUXiTt7s2v7BK67NNNClfJbuWRII1DeMaeEuqPD57HUEd3q/Rlbck2HQM9wZ9QxKzsfv2kI9selIXMb/cL+aJa7nh22+C1GbgNB3Je0dbHGCIUqdWS3hY2mdqmtcFizsq9S3SoJBaFoLYKPA6Q8Bqrc2GHRDzd5x0WZzylROvCJakAZSDiS+vMpVH4hocE6Z9/nsGJAR70DF23tN4VIx07Lw0ZR6FfmevsdKRr4s558uVO77Ol9qZcMb0BmRobGIlifH/xEarzvjYtmYqb8cvZWidlzu9mX1UQxNdiBnB0eecSGxwUPBJBqrCtubNryTyl7nC7w6wRAV5fr/ivWCvHeW4BLcpUQujrtIuEkFFGcOHQtsWptAP/lGklIKDdO2/ibrrRDiVzY12cDf/+vFjaAwVz/jEfZJ5C3MgMm5hrv9ddLB5ivjfUnp/yxiI9i/wiT9amE8H+BK3CEjGCKW+m5b4+8LS08n0PPKZW2YT+EG3M4qm1J5ClepVhAOc1IMI6ZzyPAxgb8Y47t+kooDaLxzH/gBhtICKh3COoS4jZfJZrNf0lOqtfQ2NoQ9Ll/QXT0yj3Tam322pJ4NK47jI56IxBkPOkdeiZWfGWNVVSn+ndU6EHxrUN6FVgliber/Gs=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: lumen-credentials
      namespace: lumen
    type: kubernetes.io/basic-auth
---