---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lumen-credentials
  namespace: lumen
spec:
  encryptedData:
    password: AgCZ86pgJZ1aB4L8CKgGcN7FsTLjzAFPp225nAt7ovFC6Q9CYHXUxHGIkN6nAlPHbfztFGKjZYI9X9eZT3JZ18kqiHPHCIo0Or4iqKSeTw73NRIZxAfHwy+N0Dt6d1fT3GoXdxoMPgZo+gknU3mDNIIBDz82W3Utu6YhIvQcwSO/YHhroPOMtG1wauUMQBkKZUbkTJ9uD9i2DyHzDDdwnVzG9eVl4txgSyeYyFd5pgV57PyHF3K94zZ1VLvIo1VyBt+hi73mbbH27Kz3aZBrgZyAJeAi7CRoTCnUk37P0CEjyy0GUZtDKNy7JoexUCEKh0RzTRFey9Aww5SR6DNWk9g/9XIDeC0VRhHRz8YaoNluU2c/Ds8tu/2aOQCxgQ7rDqLXCQSREaHCMHMa31Z4SD5xq0UTRLmo26ZdX+UdI5lE8KOLfVYOtfRqq7/izA6Sh7GM81VIbbtAqLO4qecjLJyCqlw88TYxuXO843Q66h/7s3xJLL/nTPKfDVApOSv3XGIXkVAeeubT9wUuRbCvcpR5UOROnnh/srjLewtFFHXMCHy8yw+oeSLo/OVwODuriP6rRvvlmT14O2TUKUAQxKZiHVTj0gCAo0VbhgZyN+dtYj0Wrm4/TqoS1L+dHthrDRqRc/6bfC0pazNhms6Y2sPQAemOxNCBc4R1LPGaNCi3Ce2+LK87B3gE8t6VF/qJBNAg44/gjIMx0sQ1Cwvw3AVdS7NMf3Q=
    username: AgAlZVzmdG+DepJwZzG//kyAPj4sNXSbY24ep+Hhm0euVCh4I6yYD6wXQaOp01rc8y/c8YoqbGkyQncE+R0+dT+aLRH+sFx/zv0SbqrNKnDXtO4kyMS/EbAdpgw0UVjkkquQop2RPAMQK2SeXLiQWzXXf960OiJIx0IIPGcWFkiZUA2WXTQ7dbpLDbR3IIwcxVXRZl04ZL35iNDJDf2M15KZukG5t6XXunPjgc6L+n/g+gu/TwvhStDNY97d9WTnCYAjsfv/KoNx3B736sLxOJ3A3c+DTuJaEGsZPSUmDytg+i2lPYbZE5qaeGDYNEqtN9EDHTKSl1twMHHiRZaL0iv2eY9iOcjYhoO+c6uD66lnvdLp1YmAL+fDxUBT4hkCmf3+F/re67th7R9+Xnhb2n03RGeFRSSLzZednPWNSWKgaQBnEFzZOqKBP3f1A6iH1d8n6g9ZdRiLmDgsphuZzocpEXO1X59dWPmihHIikaiosRSd0F4DKJJSvf5vf277gF2dMiOJvnI6BzkvQLiAKcu/qeoGb7snOOgJs6S+JAfzF/CI+6d11/EmYKY7lGShRZRoN7aIcuJNOmAjFBdVMclP8cS/6LAskoej36hFug8TxCpCgT569NfMePnx4sBWeEf8JS6OfN/kkSP3aXJU1nnoltsH9z6JbcgtKOjTslqNZ7Fi7I/viCHi+PgQ63+7z86ImXDt21P7cF8=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: lumen-credentials
      namespace: lumen
    type: kubernetes.io/basic-auth
---
