---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBEAT7RxSQdvRIP0vkxATwyMUMajXqYtd+6sHT2GdmDl1aYS0vzf23+Fuh2NBSz/NS9MyGwEWGqqtOchiwj6Gjc9vynj8dT4+9D3NBZrX1NWSP/EVGP01qUZa6+G9EYRUhPDDm4zyf0r9zXYU6ETU9QnDuRaNDHusTIdPb0Tab/50pE50u0beSmTkOWWltwg3l53N7L7dQj43Y/f1gRkKBcDWJ/LiIUXd5GvHA/jVHxrkrnXwrkDoXus/NZiKR6tJCMo6c7x1vcbtFbky2SOAQ/wDCeTKxjwS168bjMeo8UrBDlyCjfv/CRYi0g5gBCLYmWO3MR0IcM0ynsbZoNsyRKtzi28pYTpxpNRtZqVMQwvfnIaGI2lpztwwbGcr7vsvBMp5qu6SLd9M14ofVdo9mzB3ym2TkfeuVujYNRH7Ks/PBSyVfRg9nb8xjI6+iAd4ofafLeZ1Ma1fFydJ7YpglW+I7Y1LbkRtQyrJnH6fWvPhuY48Vio3Rpa89XNfhZpQH3lFHoPsC/ajodNU3GM7Kg6kmeVgXsbZPzB6DNS+Drb3lNJA11REzCcaiToLnepHZBF5ifYX8KIwzwVWeEVyybUXwEakU9M4Uu7WVYNVez9tZ4NeKCRa0KGzGpXwFeKzGgj83Js5f88wcKRvCAY46AuU+WygUJg2h5EEnpoarqlqSrYHtG1eu1VDsLZ9uVqJtn9MwXquWoH4T52sdI1pQLy5oFR5TknzIa0q0LpCFbvgkEVPdbRA==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-token
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: k8s-github
  namespace: flux-system
spec:
  type: github
  events:
    - 'ping'
    - 'push'
  secretRef:
    name: webhook-token
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: flux-system
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: flux-system
spec:
  type: LoadBalancer
  selector:
    app: notification-controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9292
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: flux.garu.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webhook-receiver
                port:
                  number: 80
  tls:
    - hosts:
        - flux.garu.io
      secretName: webhook-receiver-tls

