---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-api-token
  namespace: hass
spec:
  encryptedData:
    token: AgBaO72uzjeMGhvghN2Hy8YL/s2GK1okkqUYn4zriMDnIlCBxJ2HYZZGiEqeHC4YprUEo2Btxvy0DTCmUtaPy7VVLKHMQcB9dMnnwvu4fB4Vpt/jpI4tc8n7qVctnSXiZmnOGuUMVt8tN0HKspBSaFgeFxlAFVlgn6z9v3GHq9zOt9kjjaHrDrdwR5j2BpcE6zZbNcaHI3pOTeqz8nb2ObSBKwyZmnEHFCrtCcRsmt3AlL2fdcsVzDekZjpBKlJwJeOaktdNZjyJ+G2UijP3StWgKWdjKvXs7AoupCnwjg+2jhyarBjaWB+6/HaK6hruT3nkg+iaVBxH2geyhWG9dg9TUD0fG+qZmq+AQuxhNKma7u1fLYqRn5CeMjIuQAs/x76nPRYTrHHFNnU8esMUQb8VmI2F/3ITgdMtvXIOzMi3S9iIij9PkeI3tdRN4jLQ/Mx8Z0HHgwAptn9Usx+oCvO4vXico/yJQ+NhpWiIXZpZcMVp3oj1yIDFw2IALTfIZuk7vyxRNZ+OL39jeW5cvTAJMhzza5zsj6d8paR9Fa2aq34doqkscGj9LTBTlVY9D3C/tAULYh1R5kAQv7XyaPZn7HT4gMYsilUsdxK4otHE6va4dM4q1uj+J/cwk2qfIKZiNjXhi21Kue7mXiaZx8f3xjR8c2autslpT8E/Rk8jPIiqMrxvhSCaMT0PJfi07ceKNqzhcHhAkGJkBKqKmuhfvF9NVhAIpV18qBxbLH1bBxC4bE5J0axmFbq2eD74GOfBmvd7ZjeV98it9DJCaiGyqtGcYSkd9q0/ugJDzb0JKGm6UykmfomIAYJyvqtFrhvcT3KtvgoEbSLF1qCjlZhHHWAK93p6ZHiRHhyH0ul9xpxoldsK374HT+PGdL3OdHqm21Y2B5D9+pQLDxf3Ni4Vt5vvCYbd1DozGZ4NOEvdV6/hwUFbExc=
  template:
    metadata:
      creationTimestamp: null
      name: hass-api-token
      namespace: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
  namespace: hass
spec:
  endpoints:
    - authorization:
        credentials:
          key: token
          name: hass-api-token
          optional: false
      port: http
      path: /api/prometheus
      interval: 60s
  namespaceSelector:
    matchNames:
      - hass
  selector:
    matchLabels:
      app: hass
---
