---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hass-api-token
  namespace: hass
spec:
  encryptedData:
    token: AgDIt7PEuIWnpxMaco1fk+KEi93hSbAfHS7oH1T4BPoLChdJueHSxYO2UKQgwWBrbgu5y/A92MtxxltjjsZQVkhSIgzZBYO/o2KeqpEjiRLYHK3LgT9xNtbN/p9M5Mc892J5Ed2rAfp3/OZI0Snd1yuMyFRH46utzfbsLhULYBHhfskuw0TCKkvn8FDQdjE52ls5v4NyOdRtkEmw3OsLM8muOglvI7wCRkcizVMXendwqFuXRax5q1W77CoCPJMGG5jyXYyLxpvbU5bPUC5iOn9sjJC62IxV7AutV6TfGwxLq06hKb8n3WyvZf2nrJmv1/LoWqIfV+F6N7s19yZYjrTNPNqveyVHAiv6dnf9nxq816ArxObnyLPOTeTZAY2MWVOVEJgMScYe7cGTyg9K/oYVi5E6Ltlm+T6WT/abfjY0HR216YPls2TDumDJ/7pZA0C1GUXZHKY+XYlbk2xw2y3Hm398PQGcj9uFqR3GoSm60UcXgP/qYM2BgM6fvtezFBjWSuT5afB8zoD5i9vkjsg8Vz9wSTQdqRDjOgxrgJsKSqvuXo+wR6dzte16GqRRjvscXBwtnN5jB3VFdpwlTwVylMvHToDG5A0hOXrr7qQkQBvyuvPsWbwD4dQ3e3yW7GrJjFI7p1bCxeoknLKsbz/KvS0I36R6sT9GZSyZAVS2+/OiGHPq36Kg/k9J5dZlNN3lAEmnSi8GPkmgfijEyqBflmAxVBm7v9YaMJ5rtlgZyaHOLzVK3mNhJ6xJR5+4MyCPO1w/FSFHWpSEC7NT4+7X8cylHwaVoWu9sIRedpzoujoaSyTDfpCxmup52PFbEz8axKH9gM9iVAP+AkOeCLR3WnIDczHiag4mDcp6dqj5UlP22cHC4JsRZhgvXcnWJUg3Xam366qf4vqrvE4EtqgBZcFYpzuF0EpjOKognDAohEfolseXiQw=
  template:
    metadata:
      name: hass-api-token
      namespace: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
  namespace: hass
spec:
  endpoints:
    - authorization:
        credentials:
          key: token
          name: hass-api-token
          optional: false
      port: http
      path: /api/prometheus
      interval: 60s
  namespaceSelector:
    matchNames:
      - hass
  selector:
    matchLabels:
      app: hass
---
