---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hass-api-token
  namespace: hass
spec:
  encryptedData:
    token: AgBIZErvlhh3/TISYD4osf15eZIAe9x0UsLhyNKF+JNuIJ+ehBJk/NaL+B3rSg4L/jFidPJBmzl/PImiSfqtIJ9xSMpGNc0gSeBW1EEmK/oU9ro0P8RkRpsn2Db/jMQaV2D7zLr7SZW/urS70NAjKmp8bZen53md7B3yEFYhoRZwXtzLHrOgJorSg2S31x6/LqL105Ru9/Os9dbxFMP/XiWTbwtK3V0ktl/zWFroheCIYIQdHsmQQYFo9Pv/RLHO324U7zQycnpVdPC3cLBYE0atQ3aobbnlfc2FPDM59AttLm+CNRsUoMTGeNCl+uW+Dp9qYnV2WhC32jCjjt2ZnLiBQVrlm9La68IZKHFBNIaSyr0EKa5kZPjp2MK+1tUM5TZrTP52U1YmeLbc16EY4Jg1OftNVU0w1QfIcBom/CElT6ZpmYDWDtnBmpSFB28gmXdL4RIOnJW7H8/pl5CFmBQTm6s6sTzAf+cCV3ri0s3Se13++RDU/9AlPlOHS9aKGhFvpZEahUmsi5/TYaSgDvxKP7z7XWoRpIhCuHXYOgMrCvwt10yD91h+ZelDBQ+bmcRrZOHZ5EkdPoX67gGE3uCAgkmv88wD5ekMg1R1BKx4Uks9jDPoaCDuO9/YAwaAxQkLyBISNXvOL9kcIYJJa5t1qeJ5uWv5bqDVoqJMaZ8QiFHyMtI8rAUjyrFMRBsHWqu/RUUleKTgxKK4RpXc/+4Il22ch8pHtWIBoSitfnf4JjQlud61H+eUa87g2vlisryCk4WxS8RzxCQ1Dnia5JBorYdEfVHfiSRQXPGFhp5ZWmQV5KJ8OY0mT+gZlm3pj9rG3Ga+yD1aFG6fT5yfRQVm6HVmTyRxbALGfh5wx8Xr0xiAvYAeAdl14kOdhodoVlc4HWd622Z1YFhDpsH6omvFYlFaRegQfnsxxUS3imfjFnZoqlpneWk=
  template:
    metadata:
      name: hass-api-token
      namespace: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
  namespace: hass
spec:
  endpoints:
    - authorization:
        credentials:
          key: token
          name: hass-api-token
          optional: false
      port: http
      path: /api/prometheus
      interval: 60s
  namespaceSelector:
    matchNames:
      - hass
  selector:
    matchLabels:
      app: hass
---
