---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-api-token
  namespace: hass
spec:
  encryptedData:
    token: AgCxCOlNPzUVS5yqfzkbKANDJ/LEHm6W/+4hpByD5VIKtAldaZSbMd2xqYDGFJbZL7fINki4HnkMdzE89W5kA4Eo6+bradZPFf+twYU/Cf+Wl0IqruP2grtuXsugHJ8QtxzNW2MJo6CidC0VSAiygFHIA3TKfgLJsqEj56Lc1ESycYTk8whb0Gr4N4q4GWt6kyUUX504SoX6ngszFmCLZrXFrSlygHmbNTaxtLnMQ7k5LPpCzLEw6fu+loTcKOEgI+MTF6wKYY+Sq0hM9ej+L1Bmz9nRN+nGV1ZlTlKr8uArXp89BIyK7MeYHO+c5Ofxwmi183Nod3irzTd8u/CArLiLIEeFn0bB+T7VMQ6o0PUVOznu9KDlgm9RX68up8zxdwNsQt6lEBSh2fkELZAKwh3qkZG4164Kq8rsw+rzdCGHx5s3in3izNlXVsvNr1/IR5/QmVtr8ijeCMuSphXgqKuOpLfXRhj4lNq2SKbiXM71hqfvOVBcTCFF5zmCskAtEYHMLJXmj4ImpsnMOhc/ohXhTK53C69naezDxLyy99cOG/z3Oe4hcuvC0fb0Jp7akV1P5mKziCiMqJ9+LPciggqV92DGRTJHV0QegMpeBV9Ud+1ueT7tZ8hi3Z+lhWtjKYD2dnQdImgTY64METze74wD3cwgajDcIA3fG3+Zww3DDhTSSo/sTfPI35jtgpfJAuwQn10C09Xv75Xtjj29EI1YWTaFCV6Qr1EGD6Vs56MZOiEmhjrBMCCWMuGay574WxD6LrT9ocioskbUasMxm172w6TzId6ibFmghYTROj2ukcJROqbg7+u05UEmKV8x8T3z601qFpxc8KIhWNtK3hDR2fdALnGnZwihIDsZ83OJd78wqdcEOR+Nu0cqyHP1DjXOmcqO1WaSfqL6M1vxYD8+Q6EY9/nwTcZHIx3C7SYVlp2KJgT2wjg=
  template:
    metadata:
      creationTimestamp: null
      name: hass-api-token
      namespace: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
  namespace: hass
spec:
  endpoints:
    - authorization:
        credentials:
          key: token
          name: hass-api-token
          optional: false
      port: http
      path: /api/prometheus
      interval: 60s
  namespaceSelector:
    matchNames:
      - hass
  selector:
    matchLabels:
      app: hass
---
