---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hass-api-token
  namespace: hass
spec:
  encryptedData:
    token: AgB29qC7tn8edj/wmtjmxdxREmJkvpY0Ergwr101HQJPMeDy1JoQCBlSRo6ASj5JgG7j9aVIVPiUFhS9yYLAcTBC+WAIDtZm2lAxnKMmUlUCqNeP9F8r+sCv/foeU1lCcL8O0UypXbYV/ELnCctsBw2SY5umTiyg2vy/d0dCUEjyLwN9a9TtoMhGY7B3T9Vew9kp8iUejsOlyGlZV4V2Rv4956x0WRLDEAGTMpEvNIA8+wISpCjNSx5GjIK45svObFNNa0nDhBeaylY/l+6wHxzHRQp5DRilrcfpl6mT3AVzvpgnojNL2RNKQgpc041w0FKFMNHSEXnnKmZJGAWOKyavEIBYWNva4R/HlaM7zQd7UgJ5e1ghf1csQZrIePkkSTGECURSq1XGuRyzfzSEDxQ2rxeBv0fYB5AwCBxvyq9f3f+m+0nzDDtt//PZFcHf6WtVbVe9H9gXlGSAso74AO0ekmZXVFO6yTQhGjTuzbDXt8JbhQ0BEi/+y5G4dib3rdurwb/yTMGpRUOIBpM9qpmcbvACacLek6nOZFO+Cd1i+r6yF361I1EHfdQe3oqvZNkY8jd0hCYcI3c5yi2pCLNUTQVwdfoE8HF+N67be+VuC9tMrqf+2AYyuS9AHHZo+W4dzwtYIC/NsAeNU/9xIkLyucw4O7+XN9eiTHTFY4jyVwuxvYBmo7C0/6rJ3/3O6/aLHB/tmpb6KsmQIQmc2zj5wQYlUQ35QcLWToyUQ9vFr7pnyxDf+LNkSEeQQdxofukKFvqxdbEIg4o5Cs1mssiOdlAeYSRS54aT2PdSBVUjq03i2dhdxAk3AQyLqPmAL5rpYPMgzfIhdlEey7P7izZa+soHXSxXEfOYpE981+omFxHvZRoZiori8LmGe3AD5N7EN+Xn71UkSKwbDBlGmFJ8/5VLeOR4oPTOApDjHOeaQ5TWiWRJxG4=
  template:
    metadata:
      creationTimestamp: null
      name: hass-api-token
      namespace: hass
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hass
  namespace: hass
spec:
  endpoints:
    - authorization:
        credentials:
          key: token
          name: hass-api-token
          optional: false
      port: http
      path: /api/prometheus
      interval: 60s
  namespaceSelector:
    matchNames:
      - hass
  selector:
    matchLabels:
      app: hass
---
