---
## MinIO Tenant Definition
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio-operator
  labels:
    app: minio
  annotations:
    prometheus.io/path: /minio/prometheus/metrics
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"

spec:
  image: minio/minio:RELEASE.2021-04-06T23-11-00Z
  imagePullPolicy: IfNotPresent
  credsSecret:
    name: garu-creds-secret
  pools:
    - servers: 1
      volumesPerServer: 1
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          nodeSelector:
            "garu.io/storage-type": "ssd"
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
  console:
    consoleSecret:
      name: garu-console-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio
  namespace: minio-operator
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

spec:
  rules:
    - host: s3.garu.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-hl
                port:
                  number: 9000
  tls:
    - hosts:
        - s3.garu.io
      secretName: minio-s3-cluster-tls
---
