apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds-secret
  namespace: minio-operator
spec:
  encryptedData:
    accesskey: AgAtmQcYTd/X3jaRSZyPpa5+G8jkTIAppsblq/Vfv/QCff5cSH9FuviqQXflHvuwDJzSFdjBEzpnrgdgfF+x4i1MIxcBGVtLftRc2fs/Ved9eYsnMrpVykRpsyf5bd42GV6aLaMueMjrkTcuY+231qifYesbXv0XYM3WA8ODYEXA/E2LOwcE4yQ4zDucVVb5Cp8tguj2wrDpNUH8YD/zhsk6MM3JH/C9BYxzENVgbmmriJdGRtUTaYtpNRSvqZW1366vR2Bk0QdjtggjjQggmfdgZzVHy0wb2P2p/7dymbCH0iXAAOG2nQfmVPUBPBSM76tDAEaMfVXgUdwaunBMQdvLWLmZT1PZ6HM019xg6wjjHy2if6ZY3JBA0XVBzDOgaeIpKndi6JAq/Cc/BNytyS/Lp4KXjcrwFy2InLXtRtUOaN8neIcU9SMPONLU8NCqClT6PeKKmaSGQDBW87sD9o1eZ+AetFrfq5NsRBZA5j5JPZzZwrIqwVHuhIthCJj0jPsGawbGDWujn3nQtiog15+z+kRhnVXMXX+NDB1MqPZCo2NgCVyWjodN5Fgjo+DB2L/JO5MNCYIKdhSsW2ulnqrGReDd7lxd9IzmOKb/z+LudupeqMjQZl9xgEhJenK/BWGgLVqYPK/nLkiF/0j26rvabROU2C4qCTqIjiLkO268HTGCDdzWtCQOKHqx8OxlnBoRX16wV7JZYdeM
    secretkey: AgA1SCsTWqvOf1qybAs/EyWGBnGa3ymgrouM0mGekOwjNBlcb2AT4g6nrmQWFdf1mxY3bdMgk/KvoonVWo8cJKNwtTDYELx7BHGYPcMk7/fJMbQmgeehs69TBs5fD/pXeL0/RbrK1lOyxXJD+2NKgzY1ziBqRW8BSXwdfqUc06bQVkdYrxe9SVcsoTL9HqouRg6v02UD/tCienT1Cp5z8HqLYMBg8Ndmpe7airBFghn63Gc+7VpGhffKPNGKZTnnyePna39FNlxrCKKNtVcISKaqcx6Fq9AqLWdzqeOK0JjZrfrLTaQDktoYg6gneFijWlYLLUICUirZU31cF9TJV5l4NCdhgcpSSWNi/wYWtAJ/IYpY/NS5yNXRDjdWpv/VCT9CbIl71LAZT7aNpkUGWWNbh5G693UKRpiA5qBYJlgq9IiqK82S1/h0X3LRG7hpOsQb+Akrs0Ywvt5s2LcDyua8fkazjLXmOEOU0N+KARzJJ2PFB72ZY8RaYCxz5hoggmB/YziQjCO0kUuFza4s8r0Yo4KD/iuDtxCFKCXVPg0yCb10zjnLnh8I1tpMfPmTlMK0QDMbZCSh9SCzNca/XNX6x2+xfN1L51ErPRwrVc/1NPi18bXG22OV0g9Ek++3qjq6vw8DQJSzpvk88Yb21xRXgokG2b9thCQF3jvShf/8KQlbwQImulI97VsbmeqX1bByIAZT/MWyHaPkOfskwQ==
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds-secret
      namespace: minio-operator
    type: Opaque
