apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/kube-system
  - ../../base/cert-manager
  - ../../base/metal-lb
  - ../../base/ingress-nginx
  - ../../base/flux-system
  - ../../base/storage/local-path-provisioner
  - ../../base/monitoring/prometheus
  - ../../base/metrics-server
  - ../../base/minio
