apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metal-lb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metal-lb
        namespace: flux-system
      interval: 10m
---

