apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: kube-system
spec:
  addresses:
    - 192.168.1.200-192.168.1.255
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adv
  namespace: kube-system
spec:
  ipAddressPools:
  - pool
