---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  values:
    controller:
      kind: DaemonSet
      hostNetwork: false
      allowSnippetAnnotations: true
      service:
        externalTrafficPolicy: Cluster
      hostPort:
        enabled: true
        ports:
          http: 80
          https: 443
      resources:
        requests:
          cpu: 100m
          memory: 150Mi
        limits:
          cpu: 400m
          memory: 300Mi

      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
