name: E2E cluster test
on:
  - pull_request
jobs:
  cluster-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: e2e test
        run: |
          echo $TEST_SSH_PRIVATE_KEY > ssh/id_rsa
          BRANCH=${{ github.ref }} ./scripts/flux-kind-e2e.sh
