name: E2E cluster test
on:
  - pull_request
jobs:
  cluster-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: e2e test
        run: |

          # install kind
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/${KIND_VERSION}/kind-linux-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/

          # install flux-cli
          curl -s https://fluxcd.io/install.sh | bash

          # install kubectl
          curl -LO "https://dl.k8s.io/release/v1.21.2/bin/linux/amd64/kubectl"
          chmod +x ./kubectl && mv kubectl $(which kubectl)

          # setup for k8s
          #swapoff -a
          #update-alternatives --set iptables  /usr/sbin/iptables-legacy || true
          #update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || true
          #update-alternatives --set arptables /usr/sbin/arptables-legacy || true

          # run tests
          mkdir ssh/ && echo $TEST_SSH_PRIVATE_KEY > ssh/id_rsa
          BRANCH=${{ github.ref }} ./scripts/flux-kind-e2e.sh
