name: 'yaml lint'
on:
  - pull_request
jobs:
  yamllint:
    name: 'yaml-lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout'
        uses: actions/checkout@master
      - name: 'lint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: .yamllint.yml
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

