---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: flux-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
  timeout: 3m
---
